from django.urls import path

from .views import (
    BalanceSheetView,
    BulkSettleView,
    BulkSettlementListView,
    DepartmentDashboardView,
    DepartmentTransactionsView,
    InvoiceListCreateView,
    InvoiceSettleView,
    BankAccountDetailView,
    BankAccountListView,
    BankImportConfirmView,
    BankImportPreviewView,
    BankTransactionBulkDeleteView,
    BankTransactionConvertView,
    BankTransactionDetailView,
    BankTransactionListView,
    JournalCreateView,
    LedgerListView,
    LedgerSummaryView,
    PendingExpenseApproveView,
    PendingExpenseListView,
    PendingExpenseRejectView,
    PendingExpenseSyncView,
    ProfitLossView,
    TrialBalanceView,
    AccountListView,
    ExpenseListView,
    ExpenseCreateView,
    IncomeListView,
    IncomeCreateView,
    FinanceDashboardView,
    OutstandingListView,
    OutstandingSettleView,
    OutstandingDashboardView,
    OutstandingReceiptView,
    GSTCenterDashboardView,
    GSTTransactionListView,
    GSTSettingsView,
    GSTSummaryReportView,
    GSTLiabilityCenterView,
    GSTR1PreparationView,
    GSTR3BPreparationView,
    ITCReconciliationCenterView,
    GSTComplianceCalendarView,
    GSTFilingHistoryView,
    GSTHealthCenterView,
    BankImportHeaderParseView,
    BankImportValidationView,
    BankImportSaveView,
    BankStatementImportListView,
    ReconciliationWorkspaceView,
    ReconciliationRulesView,
    ReconciliationAutoMatchView,
    ReconciliationMatchesView,
    ReconciliationExceptionsView,
    ReconciliationDashboardView,
    ReconciliationDuplicatesView,
    ReconciliationRiskAlertsView,
    ReconciliationAuditLogsView,
    ReconciliationReportsView,
    ReconciliationUsersView,
    FinancialAccountView,
    AccountGroupView,
    AccountsCenterDashboardView,
    AccountActivityLogView,
    AssetListCreateView,
    AssetDetailView,
    AssetAssignView,
    AssetDepreciationView,
    AssetRunDepreciationView,
    AssetDisposeView,
    AssetAuditLogView,
    AssetAllAuditLogsView,
    AssetDisposalListView,
    AssetDashboardView,
)


urlpatterns = [
    path('ledgers/', LedgerListView.as_view(), name='accounting-ledgers'),
    path('accounts/', AccountListView.as_view(), name='accounting-accounts'),
    path('expenses/', ExpenseListView.as_view(), name='accounting-expenses'),
    path('expenses/create/', ExpenseCreateView.as_view(), name='accounting-expense-create'),
    path('income/', IncomeListView.as_view(), name='accounting-income'),
    path('income/create/', IncomeCreateView.as_view(), name='accounting-income-create'),
    path('finance-dashboard/', FinanceDashboardView.as_view(), name='accounting-finance-dashboard'),
    path('journal/create/', JournalCreateView.as_view(), name='accounting-journal-create'),
    path('ledger-summary/', LedgerSummaryView.as_view(), name='accounting-ledger-summary'),
    path('trial-balance/', TrialBalanceView.as_view(), name='accounting-trial-balance'),
    path('profit-loss/', ProfitLossView.as_view(), name='accounting-profit-loss'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='accounting-balance-sheet'),
    # Pending Expense endpoints
    path('pending-expenses/', PendingExpenseListView.as_view(), name='accounting-pending-expenses'),
    path('pending-expenses/sync/', PendingExpenseSyncView.as_view(), name='accounting-pending-expenses-sync'),
    path('pending-expenses/<int:pk>/approve/', PendingExpenseApproveView.as_view(), name='accounting-pending-expense-approve'),
    path('pending-expenses/<int:pk>/reject/', PendingExpenseRejectView.as_view(), name='accounting-pending-expense-reject'),
    # Outstanding endpoints
    path('outstandings/', OutstandingListView.as_view(), name='accounting-outstandings'),
    path('outstandings/dashboard/', OutstandingDashboardView.as_view(), name='accounting-outstandings-dashboard'),
    path('outstandings/bulk-settle/', BulkSettleView.as_view(), name='accounting-outstandings-bulk-settle'),
    path('outstandings/<int:pk>/settle/', OutstandingSettleView.as_view(), name='accounting-outstanding-settle'),
    path('outstandings/<int:pk>/receipts/', OutstandingReceiptView.as_view(), name='accounting-outstanding-receipts'),
    # Bulk Settlement folders
    path('bulk-settlements/', BulkSettlementListView.as_view(), name='accounting-bulk-settlements'),
    # Invoice endpoints
    path('invoices/', InvoiceListCreateView.as_view(), name='accounting-invoices'),
    path('invoices/<int:pk>/settle/', InvoiceSettleView.as_view(), name='accounting-invoice-settle'),
    # Bank Statement Import (parse + confirm flow)
    path('bank-import/preview/', BankImportPreviewView.as_view(), name='accounting-bank-import-preview'),
    path('bank-import/confirm/', BankImportConfirmView.as_view(), name='accounting-bank-import-confirm'),
    # Banking Module
    path('bank-accounts/', BankAccountListView.as_view(), name='accounting-bank-accounts'),
    path('bank-accounts/<int:pk>/', BankAccountDetailView.as_view(), name='accounting-bank-account-detail'),
    path('bank-transactions/', BankTransactionListView.as_view(), name='accounting-bank-transactions'),
    path('bank-transactions/bulk-delete/', BankTransactionBulkDeleteView.as_view(), name='accounting-bank-transactions-bulk-delete'),
    path('bank-transactions/convert/', BankTransactionConvertView.as_view(), name='accounting-bank-transactions-convert'),
    path('bank-transactions/<int:pk>/', BankTransactionDetailView.as_view(), name='accounting-bank-transaction-detail'),
    # Department Dashboard
    path('departments/', DepartmentDashboardView.as_view(), name='accounting-departments'),
    path('departments/transactions/', DepartmentTransactionsView.as_view(), name='accounting-department-transactions'),
    # GST Center
    path('gst/dashboard/', GSTCenterDashboardView.as_view(), name='accounting-gst-dashboard'),
    path('gst/transactions/', GSTTransactionListView.as_view(), name='accounting-gst-transactions'),
    path('gst/settings/', GSTSettingsView.as_view(), name='accounting-gst-settings'),
    path('gst/summary/', GSTSummaryReportView.as_view(), name='accounting-gst-summary'),
    path('gst/liability/', GSTLiabilityCenterView.as_view(), name='accounting-gst-liability'),
    path('gst/gstr1/', GSTR1PreparationView.as_view(), name='accounting-gst-gstr1'),
    path('gst/gstr3b/', GSTR3BPreparationView.as_view(), name='accounting-gst-gstr3b'),
    path('gst/itc-reconciliation/', ITCReconciliationCenterView.as_view(), name='accounting-gst-itc-reconciliation'),
    path('gst/compliance-calendar/', GSTComplianceCalendarView.as_view(), name='accounting-gst-compliance-calendar'),
    path('gst/filing-history/', GSTFilingHistoryView.as_view(), name='accounting-gst-filing-history'),
    path('gst/health/', GSTHealthCenterView.as_view(), name='accounting-gst-health'),
    # Bank Reconciliation Foundation
    path('bank-import/parse-headers/', BankImportHeaderParseView.as_view(), name='accounting-bank-import-parse-headers'),
    path('bank-import/validate-statement/', BankImportValidationView.as_view(), name='accounting-bank-import-validate-statement'),
    path('bank-import/save-statement/', BankImportSaveView.as_view(), name='accounting-bank-import-save-statement'),
    path('bank-statement-imports/', BankStatementImportListView.as_view(), name='accounting-bank-statement-imports'),
    path('bank-statement-imports/<int:pk>/', BankStatementImportListView.as_view(), name='accounting-bank-statement-import-detail'),
    path('reconciliation/workspace/', ReconciliationWorkspaceView.as_view(), name='accounting-reconciliation-workspace'),
    path('reconciliation/rules/', ReconciliationRulesView.as_view(), name='accounting-reconciliation-rules'),
    path('reconciliation/auto-match/', ReconciliationAutoMatchView.as_view(), name='accounting-reconciliation-auto-match'),
    path('reconciliation/matches/', ReconciliationMatchesView.as_view(), name='accounting-reconciliation-matches'),
    path('reconciliation/exceptions/', ReconciliationExceptionsView.as_view(), name='accounting-reconciliation-exceptions'),
    path('reconciliation/dashboard/', ReconciliationDashboardView.as_view(), name='accounting-reconciliation-dashboard'),
    path('reconciliation/duplicates/', ReconciliationDuplicatesView.as_view(), name='accounting-reconciliation-duplicates'),
    path('reconciliation/risk-alerts/', ReconciliationRiskAlertsView.as_view(), name='accounting-reconciliation-risk-alerts'),
    path('reconciliation/audit-logs/', ReconciliationAuditLogsView.as_view(), name='accounting-reconciliation-audit-logs'),
    path('reconciliation/reports/', ReconciliationReportsView.as_view(), name='accounting-reconciliation-reports'),
    path('reconciliation/users/', ReconciliationUsersView.as_view(), name='accounting-reconciliation-users'),
    
    # Accounts Center
    path('financial-accounts/', FinancialAccountView.as_view(), name='accounting-financial-accounts'),
    path('financial-accounts/<int:pk>/', FinancialAccountView.as_view(), name='accounting-financial-account-detail'),
    path('account-groups/', AccountGroupView.as_view(), name='accounting-account-groups'),
    path('account-groups/<int:pk>/', AccountGroupView.as_view(), name='accounting-account-group-detail'),
    path('accounts-center/dashboard/', AccountsCenterDashboardView.as_view(), name='accounting-accounts-center-dashboard'),
    path('accounts-center/activity/', AccountActivityLogView.as_view(), name='accounting-accounts-center-activity'),

    # Asset Management
    path('assets/', AssetListCreateView.as_view(), name='accounting-assets'),
    path('assets/dashboard/', AssetDashboardView.as_view(), name='accounting-assets-dashboard'),
    path('assets/run-depreciation/', AssetRunDepreciationView.as_view(), name='accounting-assets-run-depreciation'),
    path('assets/audit/', AssetAllAuditLogsView.as_view(), name='accounting-assets-audit-all'),
    path('assets/disposals/', AssetDisposalListView.as_view(), name='accounting-assets-disposals'),
    path('assets/<int:pk>/', AssetDetailView.as_view(), name='accounting-asset-detail'),
    path('assets/<int:pk>/assign/', AssetAssignView.as_view(), name='accounting-asset-assign'),
    path('assets/<int:pk>/depreciation/', AssetDepreciationView.as_view(), name='accounting-asset-depreciation'),
    path('assets/<int:pk>/dispose/', AssetDisposeView.as_view(), name='accounting-asset-dispose'),
    path('assets/<int:pk>/audit/', AssetAuditLogView.as_view(), name='accounting-asset-audit'),
]

