# Generated by Django 5.2.12 on 2026-04-22 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_outstanding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='settlement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_outstandings', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='OutstandingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/outstandings/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('outstanding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting.outstanding')),
            ],
        ),
    ]
