# Generated by Django 5.2.11 on 2026-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_outstanding_receipt_and_settlement_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
