# Generated by Django 5.2.11 on 2026-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_department_to_income_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
