# Generated by Django 5.2.12 on 2026-04-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pendingexpense'),
        ('accounting', '0009_add_department_to_outstanding'),
    ]

    operations = [
    ]
