# Generated by Django 5.2.11 on 2026-04-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pendingexpense'),
        ('accounting', '0009_add_department_to_outstanding'),
    ]

    operations = [
    ]
