# Generated by Django 5.2.11 on 2026-04-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_merge_20260424_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='import_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
