# Generated by Django 5.2.11 on 2026-04-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_invoice_model'),
        ('accounting', '0012_bankaccount_banktransaction'),
    ]

    operations = [
    ]
