# Generated by Django 5.2.11 on 2026-04-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_merge_20260425_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('settlement_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('items_count', models.IntegerField(default=0)),
                ('outstanding_ids', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_settlements', to='accounting.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
