# Generated by Django 5.2.14 on 2026-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_account_org_id_bankaccount_org_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, help_text='The organization this setting belongs to.', max_length=120, unique=True)),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition')], default='regular', max_length=50)),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=50)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Settings',
                'verbose_name_plural': 'GST Settings',
            },
        ),
        migrations.CreateModel(
            name='GSTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense')], max_length=20)),
                ('source_module', models.CharField(choices=[('sales', 'Sales Module'), ('purchases', 'Purchases Module'), ('expenses', 'Expenses Module')], max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_type', models.CharField(choices=[('cgst', 'CGST'), ('sgst', 'SGST'), ('igst', 'IGST')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('recorded', 'Recorded'), ('filed', 'Filed')], default='recorded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('input_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('output_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('net_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Summary',
                'verbose_name_plural': 'GST Summaries',
                'unique_together': {('org_id', 'month', 'year')},
            },
        ),
    ]
