# Generated by Django 5.2.14 on 2026-06-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_bankaccount_account_name_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_class', models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash Account'), ('wallet', 'Wallet Account'), ('settlement', 'Settlement Account')], max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_groups',
                'ordering': ['name'],
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('financial_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cash_detail', serialize=False, to='accounting.financialaccount')),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('custodian', models.CharField(blank=True, default='', max_length=150)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'cash_accounts',
            },
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.accountgroup'),
        ),
        migrations.CreateModel(
            name='AccountActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('performed_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounting.financialaccount')),
            ],
            options={
                'db_table': 'account_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='financial_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_detail', to='accounting.financialaccount'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='financial_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_account_detail', to='accounting.financialaccount'),
        ),
        migrations.CreateModel(
            name='SettlementAccount',
            fields=[
                ('financial_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlement_detail', serialize=False, to='accounting.financialaccount')),
                ('provider', models.CharField(max_length=120)),
                ('settlement_frequency', models.CharField(blank=True, default='', max_length=100)),
                ('linked_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_settlements', to='accounting.bankaccount')),
            ],
            options={
                'db_table': 'settlement_accounts',
            },
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('financial_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet_detail', serialize=False, to='accounting.financialaccount')),
                ('provider', models.CharField(max_length=120)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_wallets', to='accounting.financialaccount')),
            ],
            options={
                'db_table': 'wallet_accounts',
            },
        ),
    ]
