# Generated by Django 5.2.14 on 2026-06-10 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_financialaccount_accountgroup_cashaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150)),
                ('priority', models.IntegerField(default=1)),
                ('confidence_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('exception_type', models.CharField(choices=[('no_match', 'No Match Found'), ('multiple_matches', 'Multiple Matches'), ('duplicate_candidate', 'Duplicate Candidate'), ('amount_mismatch', 'Amount Mismatch'), ('date_mismatch', 'Date Mismatch')], default='no_match', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_exceptions', to='accounting.banktransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('confidence_score', models.IntegerField(default=100)),
                ('match_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('bulk', 'Bulk Match')], default='automatic', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='accounting.banktransaction')),
                ('journal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches', to='accounting.journalitem')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
    ]
