# Generated by Django 5.2.14 on 2026-06-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_sync_existing_financial_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('wallet', 'Wallet'), ('settlement', 'Settlement')], max_length=20),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('asset_code', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('computer', 'Computer & IT'), ('furniture', 'Furniture & Fixtures'), ('vehicle', 'Vehicle'), ('machinery', 'Machinery & Equipment'), ('building', 'Building & Property'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('slm', 'Straight Line Method (SLM)'), ('wdv', 'Written Down Value (WDV)')], default='slm', max_length=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('under_repair', 'Under Repair'), ('fully_depreciated', 'Fully Depreciated')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('assigned_to', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounting.asset')),
            ],
            options={
                'db_table': 'asset_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(blank=True, default='System', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounting.asset')),
            ],
            options={
                'db_table': 'asset_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('disposal_date', models.DateField()),
                ('method', models.CharField(choices=[('sold', 'Sold'), ('scrapped', 'Scrapped'), ('donated', 'Donated'), ('stolen', 'Stolen / Lost')], max_length=20)),
                ('sale_proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='accounting.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'asset_disposals',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='accounting.asset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_depreciations', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'asset_depreciation',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('asset', 'period_month', 'period_year')},
            },
        ),
    ]
