# Generated by Django 5.2.14 on 2026-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_asset_management_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdisposal',
            name='method',
            field=models.CharField(choices=[('sold', 'Sold'), ('scrapped', 'Scrapped'), ('donated', 'Donated'), ('stolen', 'Stolen / Lost'), ('replaced', 'Replaced')], max_length=20),
        ),
    ]
