# Generated by Django 5.1.1 on 2025-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='shipment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
