# Generated by Django 5.1.1 on 2025-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fulfillment_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway_names',
            field=models.JSONField(default=list),
        ),
    ]
