# Generated by Django 5.1.1 on 2025-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_gateway_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_gateway_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
