# Generated by Django 5.1.1 on 2025-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_payment_gateway_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_gateway_names',
            field=models.JSONField(default=list),
        ),
    ]
