# Generated by Django 5.1.1 on 2025-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_billing_address_order_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='risk_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
