# Generated by Django 5.1.1 on 2025-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='shopify_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
