# Generated by Django 5.1.1 on 2025-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fulfillment_shopify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
