# Generated by Django 5.1.1 on 2025-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_call_attempts_order_last_called_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Batched', 'Batched'), ('Cancelled', 'Cancelled')], default='Pending', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(related_name='batches', to='core.order')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
