# Generated by Django 5.1.1 on 2025-10-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_fulfillment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Packaged', 'Packaged')], default='Pending', help_text='Internal status for the packaging workflow', max_length=64),
        ),
        migrations.CreateModel(
            name='PackagingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_assignments', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(related_name='packaging_batches', to='core.order')),
            ],
            options={
                'verbose_name': 'Packaging Batch',
                'verbose_name_plural': 'Packaging Batches',
            },
        ),
    ]
