# Generated by Django 5.1.1 on 2025-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_internal_fulfillment_status_packagingbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
