# Generated by Django 5.1.1 on 2025-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_fulfillment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='internal_fulfillment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Packaged', 'Packaged'), ('On Hold', 'On Hold')], default='Pending', help_text='Internal status for the packaging workflow', max_length=64),
        ),
    ]
