# Generated by Django 5.1.1 on 2025-10-10 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_internal_fulfillment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Reason why the order was put on hold from packaging.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaged_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
