# Generated by Django 5.1.1 on 2025-10-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_hold_reason_order_packaged_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hold_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='hold_history',
            field=models.JSONField(blank=True, default=list, help_text='A history of reasons why the order was put on hold.'),
        ),
    ]
