# Generated by Django 5.1.1 on 2025-10-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_hold_reason_order_hold_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packaging_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_images', to='core.order')),
            ],
        ),
    ]
