# Generated by Django 5.1.1 on 2025-10-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_packagingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingimage',
            name='image',
            field=models.FileField(upload_to='packaging_files/'),
        ),
    ]
