# Generated by Django 5.1.1 on 2025-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_packagingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='fulfillment_order_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
