# Generated by Django 5.1.1 on 2025-10-25 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fulfillment_fulfillment_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='org_id',
            field=models.CharField(db_index=True, default='MIGRATION_DEFAULT_ORG', help_text='The Organization ID this order belongs to.', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shopify_api_key', models.CharField(max_length=255)),
                ('shopify_api_password', models.CharField(max_length=255)),
                ('shopify_shop_url', models.URLField(max_length=255)),
                ('shopify_webhook_secret', models.CharField(max_length=255)),
                ('shopify_order_prefix', models.CharField(default='JANKI', max_length=20)),
                ('shopify_api_version', models.CharField(default='2024-07', max_length=10)),
                ('shipway_email', models.EmailField(max_length=100)),
                ('shipway_license_key', models.CharField(max_length=255)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
