# Generated by Django 5.1.1 on 2025-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_org_id_shopcredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='shipway_license_key',
            new_name='shipway_email_encrypted',
        ),
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='shopify_api_key',
            new_name='shipway_license_key_encrypted',
        ),
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='shopify_api_password',
            new_name='shopify_api_key_encrypted',
        ),
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='shopify_webhook_secret',
            new_name='shopify_api_password_encrypted',
        ),
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='shopify_shop_url',
            new_name='shopify_shop_url_encrypted',
        ),
        migrations.RemoveField(
            model_name='shopcredentials',
            name='shipway_email',
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shopify_webhook_secret_encrypted',
            field=models.CharField(default='DUMMY_SECRET', max_length=255),
            preserve_default=False,
        ),
    ]
