# Generated by Django 5.1.1 on 2025-11-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcredentials',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='teammembersettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.shopcredentials'),
        ),
    ]
