# Generated by Django 5.1.1 on 2025-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_invitation_accepted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembersettings',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('teammate', 'Teammate')], default='teammate', max_length=20),
        ),
    ]
