# Generated by Django 5.1.1 on 2025-11-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_teammembersettings_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('details', models.CharField(blank=True, max_length=512, null=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='core.fulfillment')),
            ],
            options={
                'ordering': ['-datetime'],
                'unique_together': {('fulfillment', 'datetime', 'status')},
            },
        ),
    ]
