# Generated by Django 5.1.1 on 2025-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_trackingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='fulfillment_order_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='shopify_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
