# Generated by Django 5.1.1 on 2025-11-14 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_fulfillment_fulfillment_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('DELIVERY', 'Delivery/Tracking Issue'), ('RTO', 'RTO Dispute'), ('DAMAGE', 'Product Damage/Quality'), ('MISSING', 'Missing Item/Order'), ('REFUND', 'Refund/Payment Issue'), ('CANCELLATION', 'Cancellation Request'), ('OTHER', 'Other')], default='DELIVERY', max_length=50)),
                ('status', models.CharField(choices=[('NEW_FIR', 'New FIR Filed'), ('INVESTIGATING', 'Investigating'), ('PENDING_CUST', 'Pending Customer Reply'), ('PENDING_OP', 'Pending Operations'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW_FIR', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_files', to='core.order', verbose_name='Associated Order')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_cases', to=settings.AUTH_USER_MODEL, verbose_name='Filer/Agent')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.casefile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Comment',
                'verbose_name_plural': 'Issue Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
