# Generated by Django 5.1.1 on 2025-11-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_casefile_issuecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='first_place_of_contact',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp'), ('CALL', 'Call'), ('OTHER', 'Other')], default='WHATSAPP', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='casefile',
            name='latest_remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='reshipment_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='New order (if created)'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='solution_provided_text',
            field=models.TextField(blank=True, null=True, verbose_name='Solution Provided'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='description',
            field=models.TextField(verbose_name='Problem Explanation'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_cases', to=settings.AUTH_USER_MODEL, verbose_name='Person contact name'),
        ),
    ]
