# Generated by Django 5.1.1 on 2025-11-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_casefileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_history',
            field=models.JSONField(blank=True, default=list, help_text='List of call remarks and timestamps'),
        ),
    ]
