# Generated by Django 5.1.1 on 2025-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_call_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when status changed to RESOLVED or CLOSED', null=True),
        ),
    ]
