# Generated by Django 5.1.1 on 2026-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_casefile_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingimage',
            name='image',
            field=models.ImageField(upload_to='packaging_files/'),
        ),
    ]
