# Generated by Django 5.1.1 on 2026-01-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_packagingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_status',
            field=models.CharField(blank=True, help_text='Current call status (RNR, Busy, etc.)', max_length=64, null=True),
        ),
    ]
