# Generated by Django 5.1.1 on 2026-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_order_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_status_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ndr',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
