# Generated by Django 5.1.1 on 2026-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_order_current_status_order_current_status_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ndr_call_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_call_history',
            field=models.JSONField(blank=True, default=list, help_text='Log of all NDR call attempts: [{date, status, remark, agent}]'),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_call_status',
            field=models.CharField(blank=True, help_text="Status of the NDR call (e.g., 'Will Accept', 'RNR', 'Refused')", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_remarks',
            field=models.TextField(blank=True, help_text="Final remark to be exported for the courier (e.g., 'Please re-attempt on Monday')", null=True),
        ),
    ]
