# Generated by Django 5.1.1 on 2026-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_order_confirmed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(blank=True, help_text="Custom name like 'printed_AWB_batch_XYZ'", max_length=255, null=True),
        ),
    ]
