# Generated by Django 5.1.1 on 2026-02-09 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rto_internal_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Batched', 'Batched'), ('Unpacked', 'Unpacked'), ('Restocked', 'Restocked'), ('Discarded', 'Discarded')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='rto_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rto_remarks',
            field=models.TextField(blank=True, help_text='Damage or QC remarks', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rto_restocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RTOBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch ID e.g., RTO-20260209-01', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Processed', 'Processed')], default='Open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='rto_batch',
            field=models.ForeignKey(blank=True, help_text='The processing batch this return belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.rtobatch'),
        ),
    ]
