# Generated by Django 5.1.1 on 2026-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='shared_with_names',
            field=models.TextField(blank=True, default=''),
        ),
    ]
