# Generated by Django 5.1.1 on 2026-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_stickynote_shared_with_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='postit_attachments/'),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='attachment_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
