# Generated by Django 5.1.1 on 2026-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_stickynote_completed_at_stickynote_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='auth_method',
            field=models.CharField(choices=[('legacy', 'Legacy (API Key)'), ('oauth', 'OAuth (Partner App)')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shopify_access_token_encrypted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
