# Generated by Django 5.1.1 on 2026-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_shopcredentials_auth_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='myshopify_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
