# Generated by Django 5.1.1 on 2026-02-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_shopcredentials_myshopify_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembersettings',
            name='postit_color',
            field=models.CharField(default='#FFFD82', help_text="Hex code for user's sticky notes", max_length=7),
        ),
        migrations.AlterField(
            model_name='teammembersettings',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.shopcredentials'),
        ),
    ]
