# Generated by Django 5.1.1 on 2026-02-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_teammembersettings_postit_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='parent_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='core.stickynote'),
        ),
    ]
