# Generated by Django 5.1.1 on 2026-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_postit_comment_mentioned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(blank=True, help_text='Pincode/ZIP extracted from Shipway PII', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, help_text='State extracted from Shipway PII', max_length=100, null=True),
        ),
    ]
