# Generated by Django 5.1.1 on 2026-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_order_shipping_pincode_order_shipping_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(help_text="e.g., 'Cash on Delivery (COD)' or 'Razorpay'", max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('cod', 'Cash On Delivery (COD)'), ('partial', 'Partially Paid (PPCOD)'), ('prepaid', 'Prepaid')], max_length=20)),
            ],
            options={
                'ordering': ['payment_type', 'gateway_name'],
            },
        ),
    ]
