# Generated by Django 5.1.1 on 2026-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_paymentmethodrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intelligence_flag',
            field=models.CharField(choices=[('NONE', 'Not Analyzed'), ('GREEN', 'Green (High Trust)'), ('YELLOW', 'Yellow (Medium Risk)'), ('RED', 'Red (High Risk)')], db_index=True, default='NONE', help_text='Color-coded risk flag set by the Intelligence Bot', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Trust score from 0-100, calculated by the Intelligence Bot'),
        ),
        migrations.AddField(
            model_name='order',
            name='system_suggestion',
            field=models.TextField(blank=True, default='', help_text="Bot-generated recommendation e.g. 'High Trust: Assign Bluedart'"),
        ),
    ]
