# Generated by Django 5.1.1 on 2026-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_order_intelligence_flag_order_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Agent Config', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration should be active at a time.')),
                ('system_prompt', models.TextField(help_text='Master instructions for the AI agent in plain English. This prompt tells the agent how to evaluate orders for fraud and logistics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='agent_reasoning',
            field=models.TextField(blank=True, default='', help_text="Detailed reasoning from the AI agent about this order's risk assessment"),
        ),
    ]
