# Generated by Django 5.1.1 on 2026-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_agentconfiguration_order_agent_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash-lite', help_text="Gemini model to use, e.g. 'gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.0-flash'", max_length=100),
        ),
    ]
