# Generated by Django 5.1.1 on 2026-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_agentconfiguration_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Analytics Agent Config', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration should be active at a time.')),
                ('system_prompt', models.TextField(help_text='Master instructions for the Analytics Agent in plain English.')),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='Gemini model to use via Langchain SQL Agent', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Agent Configuration',
                'verbose_name_plural': 'Analytics Agent Configurations',
            },
        ),
    ]
