# Generated by Django 5.1.1 on 2026-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_customer_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='intelligence_flag',
            field=models.CharField(choices=[('NONE', 'Not Analyzed'), ('GREEN', 'Green (Low Risk)'), ('YELLOW', 'Yellow (Medium Risk)'), ('RED', 'Red (High Risk)')], db_index=True, default='NONE', help_text='Color-coded risk flag set by the Intelligence Bot', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='system_suggestion',
            field=models.TextField(blank=True, default='', help_text="Bot-generated recommendation e.g. 'Low Risk: Assign Bluedart'"),
        ),
    ]
