# Generated by Django 5.1.1 on 2026-03-09 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_order_intelligence_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ndr_escalation_count',
            field=models.IntegerField(default=0, help_text='Number of escalation rounds completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_escalation_status',
            field=models.CharField(choices=[('NONE', 'None'), ('ESCALATION_1', 'Escalation 1 (Panel Upload)'), ('ESCALATION_2', 'Escalation 2 (Re-escalated)'), ('ESCALATION_3', 'Escalation 3 (Re-re-escalated)'), ('RTO_CONFIRMED', 'RTO Confirmed'), ('DELIVERED', 'Delivered After Escalation')], db_index=True, default='NONE', help_text='Current tier in the BlueDart escalation workflow', max_length=20),
        ),
        migrations.CreateModel(
            name='NDREscalationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255, unique=True)),
                ('escalation_level', models.IntegerField(default=1, help_text='1 = Panel, 2 = Re-escalate, 3 = Re-re-escalate')),
                ('status', models.CharField(choices=[('AWAITING_PANEL_OUTPUT', 'Awaiting Panel Output'), ('AWAITING_EMAIL_REPLY', 'Awaiting Email Reply'), ('PROCESSED', 'Processed'), ('CLOSED', 'Closed')], default='AWAITING_PANEL_OUTPUT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Processing results summary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(blank=True, related_name='ndr_escalation_batches', to='core.order')),
            ],
            options={
                'verbose_name': 'NDR Escalation Batch',
                'verbose_name_plural': 'NDR Escalation Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
