# Generated by Django 5.1.1 on 2026-03-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_order_ndr_escalation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_api_type',
            field=models.CharField(default='S', help_text="'S' for Sandbox, 'P' for Production", max_length=1),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_jwt_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_licence_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='bluedart_login_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
