# Generated by Django 5.1.1 on 2026-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_shopcredentials_bluedart_api_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='sagepilot', max_length=100)),
                ('awb', models.CharField(blank=True, max_length=100)),
                ('action_code', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('landmark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('sop', 'SOP (As Per Schedule)'), ('failed', 'Failed')], db_index=True, default='failed', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
