# Generated by Django 5.1.1 on 2026-03-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_webhook_log'),
        ('core', '0066_chatmessage_task_priority'),
    ]

    operations = [
    ]
