# Generated by Django 5.1.1 on 2026-03-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_merge_0063_webhook_log_0066_chatmessage_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_prime_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('INSPECTED', 'Inspected'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected')], default='REQUEST_CREATED', max_length=50)),
                ('request_type', models.CharField(choices=[('RETURN', 'Return'), ('EXCHANGE', 'Exchange')], default='RETURN', max_length=20)),
                ('awb_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='core.order')),
            ],
        ),
    ]
