# Generated by Django 5.1.1 on 2026-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='return_prime_token_encrypted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
