# Generated by Django 5.1.1 on 2026-03-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_shopcredentials_return_prime_token_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='payload_json',
            field=models.JSONField(blank=True, help_text='Stores the entire raw JSON payload of the webhook.', null=True),
        ),
    ]
