# Generated by Django 5.1.1 on 2026-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_webhooklog_payload_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Stores the full Return Prime JSON payload for this request.', null=True),
        ),
    ]
