# Generated by Django 5.1.1 on 2026-03-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_chatmessage_attachments'),
        ('core', '0072_returnrequest_stocked_at_returnrequest_stocked_by'),
    ]

    operations = [
    ]
