# Generated by Django 5.1.1 on 2026-03-30 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_order_fulfilled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode', '-created_at'], name='idx_ord_pcode_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['current_status', '-created_at'], name='idx_ord_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode', 'current_status', '-created_at'], name='idx_ord_pcode_stat_created'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['status', '-datetime'], name='idx_trk_evt_stat_dt'),
        ),
    ]
