# Generated by Django 5.1.1 on 2026-03-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_order_fulfilled_at_and_more'),
        ('core', '0076_replace_chatrecipient_index_names'),
    ]

    operations = [
    ]
