# Generated by Django 5.1.1 on 2026-03-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_order_idx_ord_pcode_created_and_more'),
        ('core', '0082_personaltodoattachment'),
    ]

    operations = [
    ]
