# Generated by Django 5.1.1 on 2026-03-30 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_merge_20260330_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Meta', 'Meta'), ('Google', 'Google Ads'), ('TikTok', 'TikTok Ads')], default='Meta', max_length=20)),
                ('ad_account_id', models.CharField(help_text='e.g. act_123456789', max_length=100)),
                ('access_token_encrypted', models.TextField(help_text='System access token')),
                ('app_id_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('app_secret_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_credentials', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Marketing Credential',
                'verbose_name_plural': 'Marketing Credentials',
                'unique_together': {('shop', 'platform', 'ad_account_id')},
            },
        ),
        migrations.CreateModel(
            name='CampaignDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_id', models.CharField(max_length=255)),
                ('campaign_name', models.CharField(max_length=500)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_per_purchase_cpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.marketingcredential')),
            ],
            options={
                'ordering': ['-date', '-spend'],
                'indexes': [models.Index(fields=['credential', 'date'], name='core_campai_credent_7dc64a_idx')],
                'unique_together': {('credential', 'date', 'campaign_id')},
            },
        ),
    ]
