# Generated by Django 5.1.1 on 2026-03-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_marketingcredential_campaigndailymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(default='UNKNOWN', max_length=50)),
                ('effective_status', models.CharField(default='UNKNOWN', max_length=50)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.marketingcredential')),
            ],
            options={
                'verbose_name': 'Meta Campaign',
                'verbose_name_plural': 'Meta Campaigns',
                'unique_together': {('credential', 'campaign_id')},
            },
        ),
    ]
