# Generated by Django 5.1.1 on 2026-03-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_metacampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ad_id', models.CharField(max_length=255)),
                ('ad_name', models.CharField(max_length=500)),
                ('adset_id', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_per_purchase_cpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_daily_metrics', to='core.marketingcredential')),
            ],
            options={
                'ordering': ['-date', '-spend'],
                'indexes': [models.Index(fields=['credential', 'date'], name='core_addail_credent_8b635e_idx'), models.Index(fields=['adset_id'], name='core_addail_adset_i_139495_idx'), models.Index(fields=['campaign_id'], name='core_addail_campaig_f489d5_idx')],
                'unique_together': {('credential', 'date', 'ad_id')},
            },
        ),
        migrations.CreateModel(
            name='AdSetDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adset_id', models.CharField(max_length=255)),
                ('adset_name', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=255)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('roas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_per_purchase_cpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adset_daily_metrics', to='core.marketingcredential')),
            ],
            options={
                'ordering': ['-date', '-spend'],
                'indexes': [models.Index(fields=['credential', 'date'], name='core_adsetd_credent_0b3527_idx'), models.Index(fields=['campaign_id'], name='core_adsetd_campaig_59f0a7_idx')],
                'unique_together': {('credential', 'date', 'adset_id')},
            },
        ),
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255)),
                ('adset_id', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(default='UNKNOWN', max_length=50)),
                ('effective_status', models.CharField(default='UNKNOWN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='core.marketingcredential')),
            ],
            options={
                'verbose_name': 'Meta Ad',
                'verbose_name_plural': 'Meta Ads',
                'unique_together': {('credential', 'ad_id')},
            },
        ),
        migrations.CreateModel(
            name='MetaAdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(default='UNKNOWN', max_length=50)),
                ('effective_status', models.CharField(default='UNKNOWN', max_length=50)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='core.marketingcredential')),
            ],
            options={
                'verbose_name': 'Meta Ad Set',
                'verbose_name_plural': 'Meta Ad Sets',
                'unique_together': {('credential', 'adset_id')},
            },
        ),
    ]
