# Generated by Django 5.1.1 on 2026-03-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_merge_20260330_1137'),
        ('core', '0085_diaryentry_logbook_fields'),
    ]

    operations = [
    ]
