# Generated by Django 5.1.1 on 2026-03-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_galleryitemshare'),
        ('core', '0086_merge_20260330_1440'),
    ]

    operations = [
    ]
