# Generated by Django 5.1.1 on 2026-03-31 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_addailymetric_adsetdailymetric_metaad_metaadset'),
    ]

    operations = [
        migrations.AddField(
            model_name='addailymetric',
            name='add_payment_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='add_to_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='initiate_checkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='outbound_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='reach',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addailymetric',
            name='view_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='add_payment_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='add_to_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='initiate_checkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='outbound_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='reach',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adsetdailymetric',
            name='view_content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='add_payment_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='add_to_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='initiate_checkout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='outbound_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='reach',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='view_content',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage applied to ad spend (e.g. 18.00 for India)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_settings', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Marketing Settings',
                'verbose_name_plural': 'Marketing Settings',
            },
        ),
    ]
