# Generated by Django 5.1.1 on 2026-03-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_expenseentry_transaction_type'),
        ('core', '0087_merge_0086_galleryitemshare_0086_merge_20260330_1440'),
    ]

    operations = [
    ]
