# Generated by Django 5.1.1 on 2026-03-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_addailymetric_add_payment_info_and_more'),
        ('core', '0090_leaverequest_decline_reason'),
    ]

    operations = [
    ]
