# Generated by Django 5.1.1 on 2026-03-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_merge_20260331_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='MarketingAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('insights_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_ai_insights', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
