# Generated by Django 5.1.1 on 2026-04-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_marketingaichatsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('login_customer_id', models.CharField(help_text='Manager ID', max_length=100)),
                ('customer_id', models.CharField(help_text='Target Ad Account ID', max_length=100)),
                ('developer_token_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret_encrypted', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_credentials', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Google Ads Credential',
                'verbose_name_plural': 'Google Ads Credentials',
                'unique_together': {('shop', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCampaignDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=500)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.googleadscredential')),
            ],
            options={
                'ordering': ['-date', '-spend'],
                'indexes': [models.Index(fields=['credential', 'date'], name='core_google_credent_f7c1be_idx')],
                'unique_together': {('credential', 'date', 'campaign_name')},
            },
        ),
    ]
