# Generated by Django 5.1.1 on 2026-04-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_workforce_department_workforcemember'),
        ('core', '0094_marketingaichatsession_user'),
    ]

    operations = [
    ]
