# Generated by Django 5.1.1 on 2026-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_googleadscredential_googlecampaigndailymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecampaigndailymetric',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
