# Generated by Django 5.1.1 on 2026-04-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_googlecampaigndailymetric_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecampaigndailymetric',
            name='search_budget_lost_impression_share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='googlecampaigndailymetric',
            name='search_impression_share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='GoogleAdPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=500)),
                ('ad_group_name', models.CharField(max_length=500)),
                ('ad_id', models.CharField(max_length=100)),
                ('headlines', models.JSONField(blank=True, default=list)),
                ('descriptions', models.JSONField(blank=True, default=list)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_performance_metrics', to='core.googleadscredential')),
            ],
            options={
                'indexes': [models.Index(fields=['credential', 'date'], name='core_google_credent_aa90ff_idx')],
                'unique_together': {('credential', 'date', 'ad_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleDemographicMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dimension', models.CharField(choices=[('age', 'Age Range'), ('gender', 'Gender'), ('device', 'Device'), ('location', 'Location (Region)')], max_length=20)),
                ('dimension_value', models.CharField(max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_metrics', to='core.googleadscredential')),
            ],
            options={
                'indexes': [models.Index(fields=['credential', 'date', 'dimension'], name='core_google_credent_34da2c_idx')],
                'unique_together': {('credential', 'date', 'dimension', 'dimension_value')},
            },
        ),
        migrations.CreateModel(
            name='GoogleSearchTermMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=500)),
                ('search_term', models.CharField(max_length=500)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conversions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term_metrics', to='core.googleadscredential')),
            ],
            options={
                'indexes': [models.Index(fields=['credential', 'date'], name='core_google_credent_045af0_idx')],
                'unique_together': {('credential', 'date', 'campaign_name', 'search_term')},
            },
        ),
    ]
