# Generated by Django 5.1.1 on 2026-04-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_googlecampaigndailymetric_search_budget_lost_impression_share_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDemographicMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dimension', models.CharField(choices=[('age', 'Age Range'), ('gender', 'Gender'), ('country', 'Country'), ('region', 'Region')], max_length=20)),
                ('dimension_value', models.CharField(max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchases', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impressions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_metrics', to='core.marketingcredential')),
            ],
            options={
                'indexes': [models.Index(fields=['credential', 'date', 'dimension'], name='core_metade_credent_015321_idx')],
                'unique_together': {('credential', 'date', 'dimension', 'dimension_value')},
            },
        ),
    ]
