# Generated by Django 5.1.1 on 2026-04-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_metademographicmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Marketing Agent Config', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration should be active at a time.')),
                ('system_prompt', models.TextField(help_text='Master instructions for the deep audit analysis.')),
                ('general_prompt', models.TextField(blank=True, default='', help_text='Master instructions for the general conversational chat (no payload loaded).')),
                ('model_name', models.CharField(default='gemini-2.5-pro', help_text="Gemini model to use, e.g. 'gemini-2.5-pro', 'gemini-2.5-flash'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Agent Configuration',
                'verbose_name_plural': 'Marketing Agent Configurations',
            },
        ),
    ]
