# Generated by Django 5.1.1 on 2026-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_marketingagentconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingagentconfiguration',
            name='response_style',
            field=models.CharField(choices=[('Concise', 'Concise'), ('Balanced', 'Balanced'), ('Detailed', 'Detailed')], default='Balanced', help_text="Controls the verbosity and style of the AI's response.", max_length=20),
        ),
    ]
