# Generated by Django 5.1.6 on 2026-04-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_marketingagentconfiguration_response_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=12)),
                ('entry_date', models.DateField(db_index=True)),
                ('particular', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('sub_department', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('nature', models.CharField(blank=True, default='', max_length=120)),
                ('payment_type', models.CharField(blank=True, default='', max_length=60)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_itc_eligible', models.BooleanField(default=False)),
                ('vendor_payee', models.CharField(blank=True, default='', max_length=180)),
                ('bill_due_date', models.DateField(blank=True, null=True)),
                ('approval_workflow', models.CharField(blank=True, default='', max_length=180)),
                ('cost_centre', models.CharField(blank=True, default='', max_length=120)),
                ('tds_section', models.CharField(blank=True, default='', max_length=24)),
                ('status', models.CharField(blank=True, db_index=True, default='Draft', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['org_id', 'entry_type', 'entry_date'], name='core_financ_org_id_727d93_idx'), models.Index(fields=['org_id', 'status'], name='core_financ_org_id_272ab4_idx')],
            },
        ),
    ]
