# Generated by Django 5.1.1 on 2026-04-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_marketingagentconfiguration_response_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_exchange_order',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='If this is an Exchange order generated by Return Prime, links back to the original Order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_orders', to='core.order'),
        ),
    ]
