# Generated by Django 5.1.6 on 2026-04-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_financetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('option_type', models.CharField(choices=[('department', 'Department'), ('sub_department', 'Sub Department'), ('category', 'Category'), ('nature', 'Nature'), ('payment_type', 'Payment Type')], db_index=True, max_length=32)),
                ('value', models.CharField(max_length=120)),
                ('parent_value', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['option_type', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='financeoption',
            constraint=models.UniqueConstraint(fields=('org_id', 'option_type', 'value', 'parent_value'), name='finance_option_unique_per_org'),
        ),
    ]
