# Generated by Django 5.1.1 on 2026-04-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_merge_20260402_1119'),
        ('core', '0101_order_is_exchange_order_order_parent_order'),
    ]

    operations = [
    ]
