# Generated by Django 5.2.4 on 2026-04-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_order_is_exchange_order_order_parent_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('postits', 'PostIts'), ('notes', 'My Notes'), ('tasks', 'Tasks'), ('my_chats', 'My Chats'), ('expenses', 'Expenses'), ('leave_requests', 'Leave Requests'), ('gallery', 'Gallery'), ('my_meetings', 'My Meetings')], max_length=40)),
                ('action', models.CharField(choices=[('mention', 'Mention'), ('share', 'Share'), ('reminder', 'Reminder')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('message', models.CharField(max_length=500)),
                ('preview', models.CharField(blank=True, default='', max_length=280)),
                ('entity_type', models.CharField(blank=True, default='', max_length=60)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('sub_entity_type', models.CharField(blank=True, default='', max_length=60)),
                ('sub_entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('deep_link', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiednotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='unotif_rcpt_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotification',
            index=models.Index(fields=['recipient', 'module', '-created_at'], name='unotif_rcpt_module_created_idx'),
        ),
    ]
