# Generated by Django 5.1.6 on 2026-04-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_financeoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financetransaction',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='gst_itc_eligible',
        ),
        migrations.RemoveField(
            model_name='financetransaction',
            name='gst_rate',
        ),
    ]
