# Generated by Django 5.1.1 on 2026-04-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_permission_role_workspacemembership'),
        ('core', '0103_remove_finance_gst_fields'),
    ]

    operations = [
    ]
