# Generated by Django 5.1.1 on 2026-04-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20260408_1431'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financetransaction',
            new_name='core_financ_org_id_746b50_idx',
            old_name='core_financ_org_id_727d93_idx',
        ),
        migrations.RenameIndex(
            model_name='financetransaction',
            new_name='core_financ_org_id_e9f295_idx',
            old_name='core_financ_org_id_272ab4_idx',
        ),
    ]
