# Generated by Django 5.1.1 on 2026-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_rename_core_financ_org_id_727d93_idx_core_financ_org_id_746b50_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='is_co_founder',
            field=models.BooleanField(default=False, help_text='Co-founders have the same full access as the original founder.'),
        ),
    ]
