# Generated by Django 5.1.1 on 2026-04-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_workspacemembership_is_co_founder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name for the key (e.g., 'Warehouse System')", max_length=255)),
                ('prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Shop API Key',
                'verbose_name_plural': 'Shop API Keys',
            },
        ),
    ]
