# Generated by Django 5.1.1 on 2026-04-11 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_shopapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MktAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel'), ('banner', 'Banner'), ('poster', 'Poster'), ('document', 'Document')], default='image', max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='marketing/assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_assets', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MktAssetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Shopify product ID', max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=300)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_products', to='core.mktasset')),
            ],
        ),
        migrations.CreateModel(
            name='MktAssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='core.mktasset')),
            ],
        ),
        migrations.CreateModel(
            name='MktAssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='marketing/asset_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.mktasset')),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='MktBrandMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('mention_link', models.URLField(blank=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('reach_estimate', models.IntegerField(default=0)),
                ('mention_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_brand_mentions', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-mention_date'],
            },
        ),
        migrations.CreateModel(
            name='MktCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('campaign_type', models.CharField(choices=[('social', 'Social Media'), ('offline', 'Offline / Events'), ('pr', 'Public Relations'), ('influencer', 'Influencer'), ('celebrity', 'Celebrity Endorsement'), ('ads', 'Paid Advertising')], default='social', max_length=20)),
                ('objective', models.CharField(choices=[('sales', 'Sales'), ('awareness', 'Brand Awareness'), ('leads', 'Lead Generation'), ('engagement', 'Engagement'), ('traffic', 'Website Traffic')], default='sales', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_campaigns', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MktBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.mktcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('attribution_type', models.CharField(choices=[('first_touch', 'First Touch'), ('last_touch', 'Last Touch'), ('assisted', 'Assisted'), ('linear', 'Linear')], default='last_touch', max_length=20)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_attributions', to='core.shopcredentials')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktCampaignGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.mktcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktCampaignTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.mktcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktCelebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(choices=[('actor', 'Actor'), ('model', 'Model'), ('stylist', 'Stylist'), ('designer', 'Designer'), ('musician', 'Musician'), ('influencer', 'Digital Influencer'), ('tv_personality', 'TV Personality'), ('other', 'Other')], default='actor', max_length=20)),
                ('social_followers', models.IntegerField(default=0)),
                ('agency', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_celebrities', to='core.shopcredentials')),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MktCelebrityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement_type', models.CharField(choices=[('event', 'Event Appearance'), ('photoshoot', 'Photoshoot'), ('social_post', 'Social Media Post'), ('ambassador', 'Brand Ambassador'), ('seeding', 'Product Seeding')], default='event', max_length=20)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('usage_rights', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_campaigns', to='core.mktcampaign')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeb_campaigns', to='core.mktcelebrity')),
            ],
        ),
        migrations.CreateModel(
            name='MktCelebritySpotting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, help_text='Shopify product ID', max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=300)),
                ('event_name', models.CharField(blank=True, max_length=300)),
                ('spotting_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('media_links', models.TextField(blank=True, help_text='Comma-separated media coverage URLs')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spottings', to='core.mktcelebrity')),
            ],
            options={
                'ordering': ['-spotting_date'],
            },
        ),
        migrations.CreateModel(
            name='MktCelebritySpottingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_mentions', models.IntegerField(default=0)),
                ('media_pickups', models.IntegerField(default=0)),
                ('reach_estimate', models.IntegerField(default=0)),
                ('sales_impact', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('spotting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.mktcelebrityspotting')),
            ],
        ),
        migrations.CreateModel(
            name='MktChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pr', 'PR / Media')], default='online', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_channels', to='core.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='MktInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('followers', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('bridal', 'Bridal'), ('lifestyle', 'Lifestyle'), ('beauty', 'Beauty'), ('luxury', 'Luxury'), ('celebrity', 'Celebrity'), ('micro', 'Micro-Influencer'), ('other', 'Other')], default='fashion', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_influencers', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-followers'],
            },
        ),
        migrations.CreateModel(
            name='MktInfluencerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_type', models.CharField(choices=[('paid', 'Paid'), ('barter', 'Barter'), ('affiliate', 'Affiliate'), ('gifting', 'Gifting')], default='paid', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract_url', models.URLField(blank=True)),
                ('deliverables_description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_campaigns', to='core.mktcampaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.mktinfluencer')),
            ],
        ),
        migrations.CreateModel(
            name='MktInfluencerDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('post', 'Instagram Post'), ('reel', 'Reel'), ('story', 'Story'), ('video', 'YouTube Video'), ('blog', 'Blog Post'), ('event', 'Event Appearance')], default='post', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('influencer_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.mktinfluencercampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktInfluencerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(blank=True)),
                ('platform', models.CharField(default='instagram', max_length=50)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktasset')),
                ('influencer_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.mktinfluencercampaign')),
            ],
        ),
        migrations.CreateModel(
            name='MktInfluencerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('orders_generated', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('influencer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.mktinfluencerpost')),
            ],
        ),
        migrations.CreateModel(
            name='MktLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('social', 'Social Media'), ('influencer', 'Influencer'), ('exhibition', 'Exhibition'), ('pr', 'PR Coverage'), ('celebrity', 'Celebrity Spotting'), ('ads', 'Paid Ads'), ('organic', 'Organic'), ('referral', 'Referral')], default='social', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktcampaign')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_leads', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MktLeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.mktlead')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='MktMediaPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pub_type', models.CharField(choices=[('magazine', 'Magazine'), ('newspaper', 'Newspaper'), ('blog', 'Blog / Online Media'), ('digital', 'Digital Media'), ('tv', 'Television')], default='magazine', max_length=20)),
                ('audience_size', models.IntegerField(default=0, help_text='Estimated readership / audience')),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_publications', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MktJournalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('beat', models.CharField(blank=True, help_text='e.g. Fashion, Luxury, Lifestyle', max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalists', to='core.mktmediapublication')),
            ],
        ),
        migrations.CreateModel(
            name='MktOfflineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('exhibition', 'Exhibition'), ('popup', 'Pop-Up Store'), ('trunk_show', 'Trunk Show'), ('retail', 'Retail Activation'), ('society', 'Society Event'), ('wedding_fair', 'Wedding Fair'), ('other', 'Other')], default='exhibition', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_events', to='core.mktcampaign')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_offline_events', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MktOfflineEventInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Shopify product ID', max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=300)),
                ('qty_sent', models.IntegerField(default=0)),
                ('qty_sold', models.IntegerField(default=0)),
                ('qty_returned', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.mktofflineevent')),
            ],
        ),
        migrations.CreateModel(
            name='MktOfflineEventSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.mktofflineevent')),
            ],
        ),
        migrations.CreateModel(
            name='MktOfflineExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('stall_rent', 'Stall Rent'), ('travel', 'Travel & Stay'), ('staff', 'Staff Cost'), ('logistics', 'Logistics'), ('marketing_material', 'Marketing Material'), ('setup', 'Setup & Decoration'), ('other', 'Other')], default='stall_rent', max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.mktofflineevent')),
            ],
        ),
        migrations.CreateModel(
            name='MktOfflineLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interest_type', models.CharField(choices=[('bridal', 'Bridal'), ('gifting', 'Gifting'), ('daily_wear', 'Daily Wear'), ('custom', 'Customization'), ('bulk', 'Bulk Order'), ('other', 'Other')], default='bridal', max_length=20)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.mktofflineevent')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='MktPRCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500)),
                ('article_url', models.URLField(blank=True)),
                ('coverage_type', models.CharField(choices=[('organic', 'Organic'), ('paid', 'Paid PR'), ('earned', 'Earned Media')], default='organic', max_length=20)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('estimated_reach', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_coverage', to='core.mktcampaign')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktmediapublication')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='MktPROutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outreach_date', models.DateField(auto_now_add=True)),
                ('pitch_subject', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Pitch Sent'), ('follow_up', 'Follow-up'), ('replied', 'Replied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('no_response', 'No Response')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_outreach', to='core.mktcampaign')),
                ('journalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach', to='core.mktjournalist')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktmediapublication')),
            ],
            options={
                'ordering': ['-outreach_date'],
            },
        ),
        migrations.CreateModel(
            name='MktSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spend_date', models.DateField()),
                ('spend_type', models.CharField(choices=[('ads', 'Advertising'), ('influencer', 'Influencer'), ('pr', 'Public Relations'), ('event', 'Events'), ('content', 'Content Production'), ('other', 'Other')], default='ads', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktcampaign')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mktchannel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_spend', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-spend_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter/X')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(blank=True, max_length=200)),
                ('connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='SocialHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text='e.g. luxury, bridal, daily wear', max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_hashtags', to='core.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('reel', 'Reel'), ('carousel', 'Carousel'), ('static', 'Static Image'), ('story', 'Story'), ('video', 'Video'), ('text', 'Text Post')], default='static', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.socialaccount')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='core.mktasset')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='core.mktcampaign')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.socialpost')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_products', to='core.socialpost')),
            ],
        ),
        migrations.CreateModel(
            name='MktBrandMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('branded_search_volume', models.IntegerField(default=0)),
                ('social_mentions_count', models.IntegerField(default=0)),
                ('direct_traffic', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_brand_metrics', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MktCampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('leads', models.IntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.mktcampaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MktCampaignChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_channels', to='core.mktcampaign')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_campaigns', to='core.mktchannel')),
            ],
            options={
                'unique_together': {('campaign', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='SocialPostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_posts', to='core.socialhashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='core.socialpost')),
            ],
            options={
                'unique_together': {('post', 'hashtag')},
            },
        ),
    ]
