# Generated by Django 5.1.1 on 2026-04-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_marketing_extended_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('cpa_spike', 'CPA Spike'), ('roas_drop', 'ROAS Drop'), ('general', 'General')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(help_text='AI-generated alert message from Gemini')),
                ('metric_data', models.JSONField(blank=True, default=dict, help_text="Stores delta values, 7-day avg, today's values for context")),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_alerts', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Marketing Alert',
                'verbose_name_plural': 'Marketing Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cogs_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Average Cost of Goods Sold as a percentage (e.g. 30.00 for 30%)', max_digits=5)),
                ('shipping_cost_per_order', models.DecimalField(decimal_places=2, default=50.0, help_text='Average shipping cost per order in store currency (e.g. ₹50)', max_digits=10)),
                ('target_roas', models.DecimalField(decimal_places=2, default=3.0, help_text='Target Return on Ad Spend (e.g. 3.00 means 3x)', max_digits=6)),
                ('target_cpa', models.DecimalField(decimal_places=2, default=500.0, help_text='Target Cost Per Acquisition in store currency (e.g. ₹500)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_financials', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Store Financials',
                'verbose_name_plural': 'Store Financials',
            },
        ),
    ]
