# Generated by Django 5.1.1 on 2026-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_unifiednotification'),
        ('core', '0109_marketingalert_storefinancials'),
    ]

    operations = [
    ]
