# Generated by Django 5.1.1 on 2026-04-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_merge_20260411_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('rule_name', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('Cheapest', 'Cheapest'), ('Fastest', 'Fastest'), ('Success Rate', 'Highest Success Rate'), ('RTO Risk', 'Lowest RTO Risk'), ('COD Allowed', 'COD Allowed')], max_length=30)),
                ('action_courier_partner', models.CharField(help_text='Courier to assign when this rule matches', max_length=100)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('partner_type', models.CharField(choices=[('Direct', 'Direct'), ('Aggregator', 'Aggregator')], default='Direct', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted API credentials for this partner')),
                ('spoc_details', models.JSONField(blank=True, default=dict, help_text='{"name": "...", "email": "...", "phone": "..."}')),
                ('rate_list', models.JSONField(blank=True, default=dict, help_text='{"local_500g": 30, "regional_500g": 50, "national_500g": 70, ...}')),
                ('active_pincodes', models.JSONField(blank=True, default=list, help_text='List of serviceable pincodes or pincode ranges')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('awb_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('courier_partner', models.CharField(choices=[('Bluedart', 'Bluedart'), ('Delhivery', 'Delhivery'), ('Aggregator', 'Aggregator'), ('Other', 'Other')], db_index=True, default='Other', max_length=50)),
                ('shipping_mode', models.CharField(choices=[('Air', 'Air'), ('Surface', 'Surface')], default='Surface', max_length=10)),
                ('zone', models.CharField(choices=[('Local', 'Local'), ('Regional', 'Regional'), ('National', 'National')], default='National', max_length=20)),
                ('weight_slab', models.DecimalField(decimal_places=2, default=0.5, help_text='Charged weight slab in KG', max_digits=6)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Partially Paid', 'Partially Paid'), ('PrePaid', 'PrePaid')], db_index=True, default='PrePaid', max_length=20)),
                ('dispatch_date', models.DateTimeField(blank=True, help_text='When the order was handed to the courier', null=True)),
                ('delivery_date', models.DateTimeField(blank=True, help_text='When the order was delivered to customer', null=True)),
                ('current_stage', models.CharField(choices=[('Order', 'Order'), ('Packed', 'Packed'), ('Manifested', 'Manifested'), ('Picked', 'Picked'), ('In Transit', 'In Transit'), ('OFD', 'Out for Delivery'), ('Delivered', 'Delivered'), ('RTO', 'RTO'), ('Lost', 'Lost')], db_index=True, default='Order', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected'), ('Remitted', 'Remitted'), ('Not Applicable', 'Not Applicable')], default='Pending', max_length=20)),
                ('total_delivery_attempts', models.IntegerField(default=0)),
                ('first_attempt_date', models.DateTimeField(blank=True, null=True)),
                ('ndr_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='The source order this shipment tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='CODRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_remittance_date', models.DateField(blank=True, help_text='When the courier should remit the COD amount', null=True)),
                ('actual_remittance_date', models.DateField(blank=True, help_text='When the COD amount was actually received', null=True)),
                ('delay_days', models.IntegerField(default=0, help_text='Days delayed past expected remittance date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Overdue', 'Overdue'), ('Mismatch', 'Mismatch')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rto_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight_discrepancy_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ndr_reattempt_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('true_cost', models.DecimalField(decimal_places=2, default=0, help_text='True Cost = Forward + (RTO probability * RTO cost)', max_digits=10)),
                ('expected_cost', models.DecimalField(decimal_places=2, default=0, help_text='Expected cost based on rate card', max_digits=10)),
                ('actual_billed_cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount billed by courier', max_digits=10)),
                ('is_overbilled', models.BooleanField(default=False)),
                ('overbilling_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='core.shipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org_id', 'courier_partner', 'payment_type'], name='idx_shp_org_cour_pay'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org_id', 'current_stage', '-dispatch_date'], name='idx_shp_org_stage_disp'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['org_id', '-dispatch_date'], name='idx_shp_org_dispatch'),
        ),
        migrations.AddIndex(
            model_name='codremittance',
            index=models.Index(fields=['status', '-expected_remittance_date'], name='idx_cod_status_date'),
        ),
    ]
