# Generated by Django 5.2.5 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_merge_20260411_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('wfh', 'WFH'), ('leave', 'Leave')], default='present', max_length=20)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('on_duty_detail', models.CharField(blank=True, default='', max_length=255)),
                ('is_regularization', models.BooleanField(default=False)),
                ('regularization_reason', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('self', 'Self'), ('hr', 'HR/Manager')], default='self', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_approved_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['org_id', 'user', 'entry_date'], name='core_attend_org_id_c0477a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['org_id', 'approval_status', 'entry_date'], name='core_attend_org_id_4364e2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['org_id', 'entry_date', 'is_active'], name='core_attend_org_id_bdcecc_idx'),
        ),
    ]
