# Generated by Django 5.1.1 on 2026-04-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_courierrule_deliverypartner_shipment_codremittance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_partner', models.CharField(db_index=True, help_text='Must match Shipment.courier_partner values (Bluedart, Delhivery, Aggregator, Other)', max_length=50)),
                ('name', models.CharField(help_text="e.g., 'Bluedart Surface Q1 2026'", max_length=200)),
                ('shipping_mode', models.CharField(choices=[('Surface', 'Surface'), ('Air', 'Air')], default='Surface', max_length=10)),
                ('pricing_mode', models.CharField(choices=[('SLAB', 'Fixed Slab (₹ per weight range)'), ('BASE_PLUS', 'Base + Additional (₹ base for first Xkg, ₹ per additional increment)')], default='SLAB', max_length=10)),
                ('cod_charge_flat', models.DecimalField(decimal_places=2, default=0, help_text='Flat COD fee per shipment (₹)', max_digits=8)),
                ('cod_charge_percent', models.DecimalField(decimal_places=2, default=0, help_text='% of order value for COD — final COD = max(flat, percent × order_value)', max_digits=5)),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, default=0, help_text='Fuel surcharge % added on base freight (e.g., 12.5)', max_digits=5)),
                ('rto_charge_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='RTO cost = forward cost × this multiplier (1.0 = same as forward)', max_digits=4)),
                ('ndr_reattempt_charge', models.DecimalField(decimal_places=2, default=0, help_text='Per-reattempt delivery charge (₹)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['courier_partner', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='zone',
            field=models.CharField(choices=[('Local', 'Local'), ('Intra-City', 'Intra-City'), ('Within State', 'Within State'), ('Regional', 'Regional'), ('Metro', 'Metro-to-Metro'), ('National', 'National'), ('Special', 'Special / Remote')], default='National', max_length=20),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(help_text="e.g., 'Main Warehouse', 'Mumbai Hub'", max_length=200)),
                ('pincode', models.CharField(help_text='6-digit origin pincode', max_length=6)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default warehouse for cost calculations')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Origin warehouse for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.warehouse'),
        ),
        migrations.CreateModel(
            name='RateSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('Local', 'Local'), ('Intra-City', 'Intra-City'), ('Within State', 'Within State'), ('Regional', 'Regional'), ('Metro', 'Metro-to-Metro'), ('National', 'National'), ('Special', 'Special / Remote')], max_length=20)),
                ('weight_from_kg', models.DecimalField(decimal_places=2, help_text='Start of weight range in KG (inclusive)', max_digits=6)),
                ('weight_to_kg', models.DecimalField(decimal_places=2, help_text="End of weight range in KG (exclusive). Use 99 for 'and above'.", max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price in ₹ — for SLAB=total price, for BASE_PLUS=per-increment price', max_digits=10)),
                ('increment_kg', models.DecimalField(decimal_places=2, default=0.5, help_text='For BASE_PLUS mode: weight increment step (e.g., 0.5 = per 500g)', max_digits=6)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='core.courierratecard')),
            ],
            options={
                'ordering': ['zone', 'weight_from_kg'],
                'unique_together': {('rate_card', 'zone', 'weight_from_kg')},
            },
        ),
    ]
