# Generated by Django 5.2.5 on 2026-04-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_attendanceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('employee_code', models.CharField(blank=True, default='', max_length=40)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('uan_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('base_monthly_gross', models.DecimalField(decimal_places=2, default=60000, max_digits=12)),
                ('tax_regime', models.CharField(choices=[('new', 'New Regime'), ('old', 'Old Regime')], default='new', max_length=10)),
                ('payment_mode', models.CharField(blank=True, default='NEFT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('org_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PayrollSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('component_name', models.CharField(max_length=120)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partly')], default='yes', max_length=10)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_salary_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('section_code', models.CharField(blank=True, default='80C', max_length=20)),
                ('investment_name', models.CharField(max_length=255)),
                ('max_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('declared_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proof_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('org_id', 'user', 'financial_year', 'section_code', 'investment_name')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('month', models.DateField(db_index=True)),
                ('working_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_reference', models.CharField(blank=True, default='', max_length=120)),
                ('payment_mode', models.CharField(blank=True, default='NEFT', max_length=30)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Processed', 'Processed'), ('On Hold', 'On Hold')], default='Paid', max_length=20)),
                ('earnings_breakup', models.JSONField(blank=True, default=list)),
                ('deductions_breakup', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_payment_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'user_id'],
                'unique_together': {('org_id', 'user', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollprofile',
            index=models.Index(fields=['org_id', 'user'], name='core_payrol_org_id_52cc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsalarystructure',
            index=models.Index(fields=['org_id', 'user', 'is_active'], name='core_payrol_org_id_3438df_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolltaxdeclaration',
            index=models.Index(fields=['org_id', 'user', 'financial_year', 'is_active'], name='core_payrol_org_id_58eb75_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentrecord',
            index=models.Index(fields=['org_id', 'month'], name='core_payrol_org_id_3c819e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentrecord',
            index=models.Index(fields=['org_id', 'user', 'month'], name='core_payrol_org_id_f0ddee_idx'),
        ),
    ]
