# Generated by Django 5.2.5 on 2026-04-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_payroll_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('month', models.DateField(db_index=True)),
                ('attendance_locked_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_run_at', models.DateTimeField(blank=True, null=True)),
                ('exception_report', models.JSONField(blank=True, default=list)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('finance_approved_at', models.DateTimeField(blank=True, null=True)),
                ('payslips_generated_at', models.DateTimeField(blank=True, null=True)),
                ('bank_file_generated_at', models.DateTimeField(blank=True, null=True)),
                ('gl_posted_at', models.DateTimeField(blank=True, null=True)),
                ('gl_reference', models.CharField(blank=True, default='', max_length=120)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_attendance_locks', to=settings.AUTH_USER_MODEL)),
                ('bank_file_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_bank_file_generations', to=settings.AUTH_USER_MODEL)),
                ('calculation_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_calculation_runs', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_finance_approvals', to=settings.AUTH_USER_MODEL)),
                ('gl_posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_gl_postings', to=settings.AUTH_USER_MODEL)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_hr_approvals', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_locks', to=settings.AUTH_USER_MODEL)),
                ('payslips_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payslip_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-updated_at'],
                'unique_together': {('org_id', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['org_id', 'month'], name='core_payrun_org_month_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['org_id', 'is_locked', 'month'], name='core_payrun_org_lock_m_idx'),
        ),
    ]
