# Generated by Django 5.1.1 on 2026-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_courierratecard_alter_shipment_zone_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierratecard',
            name='shipping_mode',
            field=models.CharField(choices=[('Surface', 'Surface'), ('Air', 'Air'), ('Apex', 'Apex / Air Express')], default='Surface', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_mode',
            field=models.CharField(choices=[('Air', 'Air'), ('Surface', 'Surface'), ('Apex', 'Apex / Air Express')], default='Surface', max_length=10),
        ),
    ]
