# Generated by Django 5.2.5 on 2026-04-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_payroll_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('registered_address', models.TextField(blank=True, default='')),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['org_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('base_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('org_id', 'user')},
            },
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='dispute_query',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='dispute_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='dispute_resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='payslip_pdf',
            field=models.FileField(blank=True, null=True, upload_to='payroll/payslips/'),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='salary_structure_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollpaymentrecord',
            name='salary_structure_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollsalarystructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='payrollsalarystructure',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollsalarystructure',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='base_monthly_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['org_id', 'user', 'is_active'], name='core_emppro_org_user_act_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsalarystructure',
            index=models.Index(fields=['org_id', 'user', 'effective_from'], name='core_payrol_org_eff_from_idx'),
        ),
    ]
