# Generated by Django 5.1.1 on 2026-04-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_courierratecard_shipping_mode_and_more'),
        ('core', '0113_payroll_run'),
    ]

    operations = [
    ]
