# Generated by Django 5.1.1 on 2026-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_merge_20260417_1155'),
        ('core', '0114_payroll_hardening'),
    ]

    operations = [
    ]
