# Generated by Django 5.1.1 on 2026-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_payroll_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
