# Generated by Django 5.1.1 on 2026-04-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_galleryitem_is_favorite_galleryitem_is_reference'),
        ('core', '0115_merge_0114_merge_20260417_1155_0114_payroll_hardening'),
    ]

    operations = [
    ]
