# Generated by Django 5.1.1 on 2026-04-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_hr_meeting_manager_company_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('courier_partner', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(help_text='invoice_date + 15 days credit period')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Seized', 'Seized (COD Offset)')], db_index=True, default='Pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AlterField(
            model_name='codremittance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Overdue', 'Overdue'), ('Mismatch', 'Mismatch'), ('Seized', 'Seized')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('disputed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.CharField(help_text="e.g. 'Weight Discrepancy (Billed 2kg, Actual 500g)'", max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Credit Note Issued', 'Credit Note Issued'), ('Rejected', 'Rejected')], db_index=True, default='Open', max_length=30)),
                ('credit_note_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('freight_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.freightinvoice')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.shipment')),
            ],
            options={
                'ordering': ['-logged_date'],
            },
        ),
    ]
