# Generated by Django 5.1.1 on 2026-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_remove_diaryentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='freight_invoices/'),
        ),
    ]
