# Generated by Django 5.1.1 on 2026-04-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_freightinvoice_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdispute',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Optional: null when dispute is raised at invoice-line level only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.shipment'),
        ),
        migrations.CreateModel(
            name='CourierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('awb_number', models.CharField(db_index=True, max_length=100)),
                ('courier_ref', models.CharField(blank=True, help_text='CCRCRDREF — our internal order ref (e.g. JANKI39337, JANKI38133RET1064)', max_length=200)),
                ('product_code', models.CharField(blank=True, help_text='Courier product code: ACL=Air-COD-fwd, APL=Air-Prepaid-fwd, AP/AC=return legs', max_length=20)),
                ('origin_area', models.CharField(blank=True, max_length=100)),
                ('dest_area', models.CharField(blank=True, max_length=100)),
                ('dest_pincode', models.CharField(blank=True, max_length=10)),
                ('commodity', models.TextField(blank=True, help_text='Product description as declared to courier')),
                ('actual_weight_kg', models.DecimalField(decimal_places=3, default=0, help_text="NACTWGT — weight measured by courier's scale", max_digits=8)),
                ('charged_weight_kg', models.DecimalField(decimal_places=3, default=0, help_text='NCHRGWT — weight slab billed on', max_digits=8)),
                ('pieces', models.IntegerField(default=1)),
                ('freight', models.DecimalField(decimal_places=2, default=0, help_text='NFREIGHT — base freight', max_digits=10)),
                ('fsc', models.DecimalField(decimal_places=2, default=0, help_text='NFSAMT — fuel surcharge', max_digits=10)),
                ('caf', models.DecimalField(decimal_places=2, default=0, help_text='NCAFAMT — carrier adjustment factor', max_digits=10)),
                ('fod_charge', models.DecimalField(decimal_places=2, default=0, help_text='NFODCHRG — COD field delivery charge', max_digits=10)),
                ('declared_value_charge', models.DecimalField(decimal_places=2, default=0, help_text='NVALCHGS — declared value / insurance', max_digits=10)),
                ('idc_charge', models.DecimalField(decimal_places=2, default=0, help_text='NIDCCHGS — in-transit damage cover', max_digits=10)),
                ('misc_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, help_text='NTOTAMOUNT — total charged for this AWB', max_digits=10)),
                ('shipment_type', models.CharField(choices=[('Forward', 'Forward Delivery'), ('Return', 'Return / RTO'), ('Exchange', 'Exchange'), ('Credit', 'Credit / Adjustment')], db_index=True, default='Forward', max_length=20)),
                ('expected_weight_kg', models.DecimalField(decimal_places=3, default=0, help_text='Expected slab under business rule (0.5 for all <250g orders)', max_digits=8)),
                ('expected_freight', models.DecimalField(blank=True, decimal_places=2, help_text='Correct freight at expected slab from rate card', max_digits=10, null=True)),
                ('expected_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total we should have been billed (freight+FSC+CAF+FOD)', max_digits=10, null=True)),
                ('overcharge_amount', models.DecimalField(decimal_places=2, default=0, help_text='total_billed - expected_total (positive = overcharged)', max_digits=10)),
                ('discrepancy_type', models.CharField(choices=[('None', 'No Discrepancy'), ('WrongSlab', 'Wrong Weight Slab'), ('WrongZone', 'Wrong Zone Charged'), ('UnexpectedRTO', 'RTO Charged Without Shipment Event'), ('UnexpectedFOD', 'FOD on Prepaid Order'), ('CreditNote', 'Credit / Adjustment'), ('NoMatch', 'AWB Not Found in Our System'), ('Multiple', 'Multiple Issues')], db_index=True, default='None', max_length=30)),
                ('discrepancy_notes', models.TextField(blank=True, help_text='Human-readable explanation of why this line was flagged')),
                ('is_disputed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.shipmentdispute')),
                ('freight_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.freightinvoice')),
                ('shipment', models.ForeignKey(blank=True, help_text='Linked Shipment record. Null if AWB not found in our system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.shipment')),
            ],
            options={
                'indexes': [models.Index(fields=['org_id', 'discrepancy_type'], name='idx_invline_disc'), models.Index(fields=['org_id', 'shipment_type'], name='idx_invline_type'), models.Index(fields=['org_id', 'is_disputed'], name='idx_invline_disputed')],
                'unique_together': {('freight_invoice', 'awb_number')},
            },
        ),
    ]
