# Generated by Django 5.1.1 on 2026-04-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_attendance_rulebook_and_autostatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('wfh', 'WFH'), ('leave', 'Leave'), ('on_duty', 'On Duty')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerulebook',
            name='early_leave_deduction_minutes',
            field=models.PositiveIntegerField(default=10, help_text='10-39 min early: Present + 1hr salary deduct'),
        ),
        migrations.AlterField(
            model_name='attendancerulebook',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=14, help_text='0-N min late: Present, warning logged'),
        ),
        migrations.AlterField(
            model_name='attendancerulebook',
            name='half_day_early_leave_minutes',
            field=models.PositiveIntegerField(default=40, help_text='N+ min early: Second Half Absent + half-day deduct'),
        ),
        migrations.AlterField(
            model_name='attendancerulebook',
            name='half_day_late_threshold_minutes',
            field=models.PositiveIntegerField(default=40, help_text='N+ min late: First Half Absent + half-day deduct'),
        ),
        migrations.AlterField(
            model_name='attendancerulebook',
            name='late_deduction_threshold_minutes',
            field=models.PositiveIntegerField(default=15, help_text='N-39 min late: Present + 1hr salary deduct'),
        ),
    ]
