# Generated by Django 5.1.1 on 2026-04-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_attendanceentry_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leave_requests/documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_action',
            field=models.CharField(blank=True, choices=[('pre_approved', 'Pre-Approved by Manager'), ('flagged', 'Flagged by Manager'), ('passed', 'Passed to HR')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mydesk_leave_manager_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('parents_birthday', "Parent's Birthday"), ('comp_off', 'Comp-Off'), ('unpaid', 'Unpaid'), ('wfh', 'WFH')], default='casual', max_length=30),
        ),
    ]
