# Generated by Django 5.1.1 on 2026-04-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_freightinvoice_invoice_file'),
        ('core', '0122_leaverequest_document_leaverequest_manager_action_and_more'),
    ]

    operations = [
    ]
