# Generated by Django 5.1.1 on 2026-04-29 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_merge_20260428_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='dept_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='dept_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='finance_entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='finance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='finance_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('posted', 'Posted to GL')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='workflow_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food & Meals'), ('office_supplies', 'Office Supplies'), ('equipment', 'Equipment'), ('client_entertainment', 'Client Entertainment'), ('misc', 'Misc'), ('other', 'Other')], default='misc', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Dept Head Approved', 'Dept Head Approved'), ('Finance Reviewed', 'Finance Reviewed'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Draft', max_length=30),
        ),
    ]
