# Generated by Django 5.1.1 on 2026-04-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_courier_invoice_line'),
        ('core', '0125_finance_payroll_verify'),
    ]

    operations = [
    ]
