# Generated by Django 5.1.1 on 2026-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_merge_20260430_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceline',
            name='expected_tax_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='expected_tax_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='expected_total_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='tax_cgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='9% CGST', max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='tax_sgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='9% SGST', max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='total_billed_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net + CGST + SGST', max_digits=10),
        ),
        migrations.AlterField(
            model_name='courierinvoiceline',
            name='expected_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total we should have been billed (Net)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courierinvoiceline',
            name='overcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total_billed_with_tax - expected_total_with_tax', max_digits=10),
        ),
        migrations.AlterField(
            model_name='courierinvoiceline',
            name='total_billed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NTOTAMOUNT — total charged for this AWB (Net)', max_digits=10),
        ),
    ]
