# Generated by Django 5.1.1 on 2026-05-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_courierinvoiceline_expected_tax_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierinvoiceline',
            name='discrepancy_type',
            field=models.CharField(choices=[('None', 'No Discrepancy'), ('WrongSlab', 'Wrong Weight Slab'), ('WrongRate', 'Wrong Unit Rate'), ('WrongZone', 'Wrong Zone Charged'), ('UnexpectedRTO', 'RTO Charged Without Shipment Event'), ('UnexpectedFOD', 'FOD on Prepaid Order'), ('CreditNote', 'Credit / Adjustment'), ('NoMatch', 'AWB Not Found in Our System'), ('Multiple', 'Multiple Issues')], db_index=True, default='None', max_length=30),
        ),
    ]
