# Generated by Django 5.1.1 on 2026-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_courierinvoiceline_discrepancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
