# Generated by Django 5.1.1 on 2026-05-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_order_current_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, db_index=True, default='', help_text='e.g. facebook, google, instagram, newsletter', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', help_text='e.g. cpc, paid, social, email, organic', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, default='', help_text='Campaign name from the UTM tag', max_length=500)),
                ('utm_content', models.CharField(blank=True, default='', help_text='Ad creative or content variant identifier', max_length=500)),
                ('utm_term', models.CharField(blank=True, default='', help_text='Keyword / Ad ID — often maps to the specific ad', max_length=500)),
                ('fbclid', models.CharField(blank=True, db_index=True, default='', help_text='Facebook/Meta click identifier', max_length=500)),
                ('gclid', models.CharField(blank=True, db_index=True, default='', help_text='Google Ads click identifier', max_length=500)),
                ('ttclid', models.CharField(blank=True, default='', help_text='TikTok click identifier', max_length=500)),
                ('landing_page', models.URLField(blank=True, default='', help_text='Raw landing_site value from Shopify API', max_length=2000)),
                ('referring_site', models.URLField(blank=True, default='', help_text='Raw referring_site value from Shopify API', max_length=2000)),
                ('channel', models.CharField(choices=[('meta_paid', 'Meta Paid'), ('google_paid', 'Google Paid'), ('tiktok_paid', 'TikTok Paid'), ('organic_social', 'Organic Social'), ('organic_search', 'Organic Search'), ('direct', 'Direct'), ('email', 'Email'), ('referral', 'Referral'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Deterministic channel from Boolean signal cascade', max_length=20)),
                ('matched_campaign_id', models.CharField(blank=True, default='', help_text='ID of MetaCampaign or GoogleCampaign matched via utm_campaign', max_length=255)),
                ('matched_adset_id', models.CharField(blank=True, default='', help_text='ID of MetaAdSet matched via utm_content', max_length=255)),
                ('matched_ad_id', models.CharField(blank=True, default='', help_text='ID of MetaAd matched via utm_term', max_length=255)),
                ('matched_platform', models.CharField(blank=True, default='', help_text="Which platform the match was found in: 'meta', 'google', etc.", max_length=20)),
                ('touch_journey', models.JSONField(blank=True, default=list, help_text="Future: Array of touchpoints from BridgeWorks pixel, e.g. [{'source': 'google_ad', 'ts': '...'}, {'source': 'fb_retargeting', ...}]")),
                ('source', models.CharField(choices=[('backfill', 'Historical Backfill'), ('webhook', 'Live Webhook'), ('pixel', 'BridgeWorks Pixel')], default='backfill', help_text='How this attribution was created', max_length=20)),
                ('backfilled_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The order this attribution data belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='core.order')),
            ],
            options={
                'verbose_name': 'Order Attribution',
                'verbose_name_plural': 'Order Attributions',
                'indexes': [models.Index(fields=['channel', '-backfilled_at'], name='idx_attr_channel_date'), models.Index(fields=['utm_source', 'utm_campaign'], name='idx_attr_src_camp')],
            },
        ),
    ]
