# Generated by Django 5.1.1 on 2026-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_add_order_attribution_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattribution',
            name='epik',
            field=models.CharField(blank=True, default='', help_text='Pinterest click identifier', max_length=500),
        ),
        migrations.AddField(
            model_name='orderattribution',
            name='fp_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='FlexyPe session ID for multi-touch attribution', max_length=255),
        ),
        migrations.AddField(
            model_name='orderattribution',
            name='referer',
            field=models.CharField(blank=True, default='', help_text='Referer value from FlexyPe tracking script note_attributes', max_length=500),
        ),
        migrations.AddField(
            model_name='orderattribution',
            name='sclid',
            field=models.CharField(blank=True, default='', help_text='Snapchat click identifier', max_length=500),
        ),
        migrations.AlterField(
            model_name='orderattribution',
            name='channel',
            field=models.CharField(choices=[('meta_paid', 'Meta Paid'), ('google_paid', 'Google Paid'), ('tiktok_paid', 'TikTok Paid'), ('pinterest_paid', 'Pinterest Paid'), ('snapchat_paid', 'Snapchat Paid'), ('organic_social', 'Organic Social'), ('organic_search', 'Organic Search'), ('direct', 'Direct'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Deterministic channel from Boolean signal cascade', max_length=20),
        ),
    ]
