# Generated by Django 5.1.1 on 2026-05-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_sales_models'),
        ('core', '0131_userpresence'),
    ]

    operations = [
    ]
