# Generated by Django 5.1.7 on 2026-05-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_merge_0129_sales_models_0131_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marketplace_platform',
            field=models.CharField(blank=True, default='', help_text='Marketplace platform name (e.g., Amazon, Flipkart, Meesho) when source=marketplace', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('marketplace', 'Marketplace'), ('retail', 'Retail Store'), ('b2b', 'B2B'), ('manual', 'Manual')], db_index=True, default='shopify', help_text='Channel/source through which this order was created', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated working capital', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='category',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], db_index=True, default='domestic', max_length=15),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='company_size',
            field=models.CharField(blank=True, choices=[('micro', 'Micro (<10 employees)'), ('small', 'Small (10-49)'), ('medium', 'Medium (50-249)'), ('large', 'Large (250-999)'), ('enterprise', 'Enterprise (1000+)')], max_length=20),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='contact_designation',
            field=models.CharField(blank=True, help_text='Job title of primary contact', max_length=100),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='credit_terms',
            field=models.CharField(blank=True, help_text='e.g., Net-30, 50% advance', max_length=100),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='customer_base',
            field=models.TextField(blank=True, help_text='Description of their customer base'),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='expected_deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry or sector of the company', max_length=100),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='mode_of_operations',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('trader', 'Trader'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='wholesalelead',
            name='products_interested',
            field=models.TextField(blank=True, help_text='Products or categories they are interested in'),
        ),
        migrations.AlterField(
            model_name='wholesalelead',
            name='stage',
            field=models.CharField(choices=[('cold_lead', 'Cold Lead'), ('contacted', 'Contacted'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('agreement_signed', 'Agreement Signed'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], db_index=True, default='cold_lead', max_length=25),
        ),
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, help_text='Full address of the store')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('manager_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_stores', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetailStoreCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('funnel_stage', models.CharField(choices=[('view_only', 'View Only'), ('purchase_intent', 'Showed Purchase Intent'), ('asked_pricing', 'Asked for Pricing'), ('initiated_billing', 'Initiated Billing'), ('purchased', 'Purchased')], db_index=True, default='view_only', max_length=20)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.retailstore')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
