# Generated by Django 5.1.1 on 2026-05-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_attribution_add_pinterest_snapchat_whatsapp_fpid'),
        ('core', '0133_order_marketplace_platform_order_source_and_more'),
    ]

    operations = [
    ]
