# Generated by Django 5.1.7 on 2026-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_merge_20260507_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcart',
            name='flexype_checkout_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='abandonedcart',
            name='session_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
