# Generated by Django 5.1.1 on 2026-05-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_merge_20260507_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('cart_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=500)),
                ('utm_content', models.CharField(blank=True, default='', max_length=500)),
                ('utm_term', models.CharField(blank=True, default='', max_length=500)),
                ('fbclid', models.CharField(blank=True, default='', max_length=500)),
                ('gclid', models.CharField(blank=True, default='', max_length=500)),
                ('ttclid', models.CharField(blank=True, default='', max_length=500)),
                ('epik', models.CharField(blank=True, default='', max_length=500)),
                ('sclid', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('referrer', models.URLField(blank=True, default='', max_length=2000)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Pixel Event',
                'verbose_name_plural': 'Pixel Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cart_token', '-timestamp'], name='idx_pixel_cart_ts'), models.Index(fields=['session_id', '-timestamp'], name='idx_pixel_session_ts')],
            },
        ),
    ]
