# Generated by Django 5.1.7 on 2026-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_abandonedcart_flexype_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcredentials',
            name='shipway_email_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shipway_license_key_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shopify_api_key_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shopify_api_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shopify_shop_url_encrypted',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shopify_webhook_secret_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
