# Generated by Django 5.1.7 on 2026-05-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_alter_shopcredentials_shipway_email_encrypted_and_more'),
        ('core', '0136_shopcredentials_optional_encrypted_fields'),
    ]

    operations = [
    ]
