# Generated by Django 5.1.7 on 2026-05-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_merge_20260509_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcredentials',
            name='shipway_email_encrypted',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcredentials',
            name='shipway_license_key_encrypted',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
