# Generated by Django 5.1.7 on 2026-05-11 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_shopcredentials_shipway_email_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abandonedcart',
            name='channel',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('marketplace', 'Marketplace'), ('retail', 'Retail Store'), ('b2b', 'B2B Leads'), ('wholesale', 'Wholesale CRM')], db_index=True, default='shopify', max_length=20),
        ),
        migrations.AddField(
            model_name='abandonedcart',
            name='channel_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ChannelDraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('shopify', 'Shopify'), ('marketplace', 'Marketplace'), ('retail', 'Retail Store'), ('b2b', 'B2B Leads'), ('wholesale', 'Wholesale CRM')], db_index=True, max_length=20)),
                ('channel_meta', models.JSONField(blank=True, default=dict)),
                ('shopify_draft_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('line_items', models.JSONField(default=list)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('prepaid', 'Prepaid'), ('cod', 'COD'), ('partially_paid', 'Partially Paid')], default='prepaid', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_draft_orders', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelAbandonedCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('shopify', 'Shopify'), ('marketplace', 'Marketplace'), ('retail', 'Retail Store'), ('b2b', 'B2B Leads'), ('wholesale', 'Wholesale CRM')], db_index=True, max_length=20)),
                ('channel_meta', models.JSONField(blank=True, default=dict)),
                ('shopify_token', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('checkout_url', models.URLField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('cart_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('line_items', models.JSONField(default=list)),
                ('recovery_status', models.CharField(choices=[('pending', 'Pending Recovery'), ('email_sent', 'Email Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('recovered', 'Recovered'), ('lost', 'Lost')], db_index=True, default='pending', max_length=20)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_abandoned_checkouts', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-abandoned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shopify_token__gt', '')), fields=('shop', 'shopify_token'), name='unique_shopify_checkout_token')],
            },
        ),
    ]
