# Generated by Django 5.1.1 on 2026-05-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_shopcredentials_shipway_email_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSoftwareCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_software_credential', to='core.shopcredentials')),
            ],
            options={
                'verbose_name': 'Production Software Credential',
                'verbose_name_plural': 'Production Software Credentials',
            },
        ),
    ]
