# Generated by Django 5.1.7 on 2026-05-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_abandonedcart_channel_abandonedcart_channel_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('meesho', 'Meesho'), ('myntra', 'Myntra'), ('nykaa', 'Nykaa'), ('ajio', 'AJIO'), ('other', 'Other')], db_index=True, default='amazon', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stage', models.CharField(choices=[('new_inquiry', 'New Inquiry'), ('negotiating', 'Negotiating'), ('sample_requested', 'Sample Requested'), ('order_placed', 'Order Placed'), ('repeat_buyer', 'Repeat Buyer')], db_index=True, default='new_inquiry', max_length=20)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_customers', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
