# Generated by Django 5.1.7 on 2026-05-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_marketplace_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelabandonedcheckout',
            name='checkout_stage',
            field=models.CharField(blank=True, choices=[('cart', 'Cart'), ('contact_info', 'Contact Info'), ('shipping', 'Shipping'), ('payment', 'Payment'), ('processing', 'Processing')], db_index=True, default='cart', max_length=20),
        ),
    ]
