# Generated by Django 5.1.7 on 2026-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_checkout_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldraftorder',
            name='customer_stage',
            field=models.CharField(blank=True, choices=[('view_only', 'View Only'), ('purchase_intent', 'Purchase Intent'), ('asked_pricing', 'Asked Pricing'), ('initiated_billing', 'Initiated Billing'), ('purchased', 'Purchased')], db_index=True, default='', max_length=20),
        ),
    ]
