# Generated by Django 5.1.1 on 2026-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_draft_order_customer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeldraftorder',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='channeldraftorder',
            name='shopify_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
