# Generated by Django 5.1.1 on 2026-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_channeldraftorder_invoice_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeldraftorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='channeldraftorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channeldraftorder',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
