# Generated by Django 5.1.1 on 2026-05-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_add_production_software_credential'),
        ('core', '0144_alter_channeldraftorder_customer_email_and_more'),
    ]

    operations = [
    ]
