# Generated by Django 5.2.14 on 2026-05-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_channeldraftorder_order_type_reference'),
        ('core', '0145_merge_20260513_1611'),
    ]

    operations = [
    ]
