# Generated by Django 5.2.14 on 2026-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_merge_20260514_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsagentconfiguration',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', help_text='Gemini model to use for the Analytics Agent', max_length=100),
        ),
    ]
