# Generated by Django 5.1.1 on 2026-05-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_alter_analyticsagentconfiguration_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAgentGlobalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField(help_text="The instruction to inject. Plain English. E.g. 'Do not recommend increasing budget on any campaign. We are in a budget freeze until further notice.'")),
                ('created_by', models.CharField(blank=True, default='admin', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = shown earlier in the prompt. Use to control rule ordering.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Rule auto-deactivates after this datetime. Leave blank for permanent rules.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Agent Global Rule',
                'verbose_name_plural': 'Marketing Agent Global Rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('user_identifier', models.CharField(blank=True, default='', help_text='Username or user ID of the person who asked the question.', max_length=255)),
                ('shop_name', models.CharField(blank=True, default='', max_length=255)),
                ('system_prompt_snapshot', models.TextField(help_text='Exact system prompt used for this API call — including all active global rules and corrections.')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('flagged_for_review', models.BooleanField(default=False, help_text='Set to True when admin flags a response for correction.')),
                ('admin_note', models.TextField(blank=True, default='', help_text="Admin's note explaining why this response was flagged.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketing Conversation Log',
                'verbose_name_plural': 'Marketing Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCorrectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_behavior_description', models.TextField(help_text="Describe the mistake the AI made. E.g. 'Recommended scaling a campaign with <50 purchases'")),
                ('corrected_instruction', models.TextField(help_text="The rule to enforce going forward. E.g. 'Never recommend scaling a campaign with fewer than 50 purchases in the period.'")),
                ('example_bad_response', models.TextField(blank=True, default='', help_text='Optional: paste the exact bad AI response here for few-shot context.')),
                ('example_good_response', models.TextField(blank=True, default='', help_text='Optional: the corrected/ideal response the AI should have given.')),
                ('source_log_id', models.IntegerField(blank=True, help_text='ID of the MarketingConversationLog entry that triggered this correction.', null=True)),
                ('created_by', models.CharField(blank=True, default='admin', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketing Correction Rule',
                'verbose_name_plural': 'Marketing Correction Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
