# Generated by Django 5.1.1 on 2026-05-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_add_agent_manager_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingagentconfiguration',
            name='persona',
            field=models.CharField(choices=[('default', 'Default (Professional Analyst)'), ('warm', 'Warm & Encouraging'), ('calm', 'Calm & Measured'), ('genz', 'Gen Z (Casual & Energetic)'), ('aggressive', 'Aggressive (Bold & Direct)'), ('zen', 'Zen (Minimal & Mindful)')], default='default', help_text="Controls the tone and personality of the AI's responses.", max_length=20),
        ),
    ]
