# Generated by Django 5.1.1 on 2026-05-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_add_persona_to_marketing_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingagentconfiguration',
            name='cogs_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated COGS Margin % (e.g. 35.00) to calculate actual ROI. Leave blank to disable.', max_digits=5, null=True),
        ),
    ]
