# Generated by Django 5.1.1 on 2026-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_add_cogs_margin_pct_to_agent_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingaichatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='marketing_ai_uploads/'),
        ),
        migrations.AddField(
            model_name='marketingaichatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
