# Generated by Django 5.2.14 on 2026-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_marketingaichatmessage_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingagentconfiguration',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash-lite', help_text="Gemini model to use, e.g. 'gemini-2.5-flash-lite', 'gemini-2.5-flash', 'gemini-2.5-pro'", max_length=100),
        ),
    ]
