# Generated by Django 5.2.14 on 2026-05-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_logisticsaichatsession_logisticsaichatmessage'),
        ('core', '0152_alter_marketingagentconfiguration_model_name'),
    ]

    operations = [
    ]
