# Generated by Django 5.1.1 on 2026-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_merge_20260521_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='internal_fulfillment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Sent for Packaging', 'Sent for Packaging'), ('Packaged', 'Packaged'), ('On Hold', 'On Hold'), ('Manifested', 'Manifested')], default='Pending', help_text='Internal status for the packaging workflow', max_length=64),
        ),
    ]
