# Generated by Django 5.1.1 on 2026-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_add_manifested_to_internal_fulfillment_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manifested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
