# Generated by Django 5.2.14 on 2026-05-25 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_logistics_agent_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsagentconfiguration',
            name='general_prompt',
            field=models.TextField(blank=True, default='', help_text='Master instructions for general conversational chat (no payload loaded).'),
        ),
        migrations.AlterField(
            model_name='logisticsagentconfiguration',
            name='system_prompt',
            field=models.TextField(help_text='Master instructions for the deep logistics audit analysis.'),
        ),
        migrations.CreateModel(
            name='RTOEngineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_status', models.CharField(choices=[('pending_qc', 'Pending QC'), ('suspicious', 'Suspicious'), ('damaged', 'Damaged'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('sent_to_inventory', 'Sent to Inventory'), ('under_investigation', 'Under Investigation'), ('investigation_resolved', 'Investigation Resolved')], db_index=True, default='pending_qc', max_length=30)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_notes', models.TextField(blank=True, null=True)),
                ('qc_at', models.DateTimeField(blank=True, null=True)),
                ('qc_notes', models.TextField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('investigation_status', models.CharField(blank=True, choices=[('open', 'Open'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rto_engine_items', to='core.order')),
                ('qc_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_engine_qc', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_engine_resolutions', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_engine_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
