# Generated by Django 5.1.7 on 2026-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_order_manifested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='currency_locale',
            field=models.CharField(default='en-IN', max_length=16),
        ),
    ]
