# Generated by Django 5.2.14 on 2026-05-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_rto_engine_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtoengineitem',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_engine_entries', to='core.lineitem'),
        ),
    ]
