# Generated by Django 5.1.1 on 2026-05-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_order_manifested_at'),
        ('core', '0156_rto_engine_item_lineitem'),
    ]

    operations = [
    ]
