# Generated by Django 5.2.14 on 2026-05-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_order_manifested_at'),
        ('core', '0157_rto_engine_item_write_off_reason'),
    ]

    operations = [
    ]
