# Generated by Django 5.2.14 on 2026-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_merge_20260527_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtoengineitem',
            name='scan_status',
            field=models.CharField(choices=[('pending_qc', 'Pending QC'), ('suspicious', 'Suspicious'), ('damaged', 'Damaged'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('sent_to_inventory', 'Sent to Inventory'), ('under_investigation', 'Under Investigation'), ('investigation_resolved', 'Investigation Resolved'), ('sent_for_repair', 'Sent for Repair'), ('written_off', 'Written Off')], db_index=True, default='pending_qc', max_length=30),
        ),
    ]
