# Generated by Django 5.2.14 on 2026-05-29 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_merge_20260528_1315'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtoengineitem',
            name='scan_status',
            field=models.CharField(choices=[('pending_qc', 'Pending QC'), ('suspicious', 'Suspicious'), ('damaged', 'Damaged'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('sent_to_inventory', 'Sent to Inventory'), ('under_investigation', 'Under Investigation'), ('investigation_resolved', 'Investigation Resolved'), ('sent_for_repair', 'Sent for Repair'), ('written_off', 'Written Off')], db_index=True, default='pending_qc', max_length=30),
        ),
        migrations.CreateModel(
            name='RTOEngineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(db_index=True)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_engine_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('org_id', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='rtoengineitem',
            name='rto_engine_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.rtoenginebatch'),
        ),
    ]
