# Generated by Django 5.1.1 on 2026-05-27 18:04
# Merge migration: unifies Sales/BD currency migration, Jatin's RTO write-off,
# and the existing RTO scan_status alter into a single migration graph.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_add_currency_to_shop'),
        ('core', '0157_rto_engine_item_write_off_reason'),
        ('core', '0158_alter_rtoengineitem_scan_status'),
    ]

    operations = [
    ]
