# Generated by Django 5.2.14 on 2026-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_rto_engine_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinginfo',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
