# Generated by Django 5.2.14 on 2026-05-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_merge_20260528_1315'),
        ('core', '0159_merge_20260527_1804'),
    ]

    operations = [
    ]
