# Generated by Django 5.1.1 on 2026-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_merge_20260528_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Dept Head Approved', 'Dept Head Approved'), ('Partially Approved', 'Partially Approved'), ('Finance Reviewed', 'Finance Reviewed'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Draft', max_length=30),
        ),
    ]
