# Generated by Django 5.1.1 on 2026-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_merge_20260528_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='store_name',
            field=models.CharField(blank=True, default='', help_text="Human-readable store/brand name, e.g. 'Janki Jewels'", max_length=150),
        ),
    ]
