# Generated by Django 5.1.1 on 2026-05-29 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_add_store_name_to_shopcredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(default='Arjun', max_length=150)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sandbox', 'Sandbox-Testing'), ('live', 'Live')], default='draft', max_length=20)),
                ('response_mode', models.CharField(choices=[('auto', 'Auto-Response'), ('manual', 'Manual-Approval')], default='auto', max_length=20)),
                ('chatwoot_inbox_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('sandbox_numbers', models.TextField(default='[]', help_text='JSON array of phone numbers whitelisted for testing')),
                ('system_prompt', models.TextField(blank=True, default='You are Arjun, the warm, polite and exceptionally helpful AI Support Executive for our storefront. Treat customers with care.', help_text='Core guidelines and character behavior instructions for the bot')),
                ('gemini_cache_id', models.CharField(blank=True, help_text='Google Gemini API Context Cache reference ID', max_length=255, null=True)),
                ('recurring_scraping', models.BooleanField(default=False)),
                ('scraping_interval', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager Directive'), ('system', 'System Notification'), ('customer', 'Simulated Customer'), ('bot', 'Simulated Bot Response')], default='manager', max_length=20)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.aiagent')),
            ],
            options={
                'verbose_name': 'Agent Audit Log',
                'verbose_name_plural': 'Agent Audit Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('url', 'URL'), ('text', 'Raw Text')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('metadata', models.TextField(default='{}', help_text='JSON string representing metadata like file name, page links, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_nuggets', to='core.aiagent')),
            ],
            options={
                'verbose_name': 'Knowledge Nugget',
                'verbose_name_plural': 'Knowledge Nuggets',
            },
        ),
    ]
