# Generated by Django 5.1.1 on 2026-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_add_store_name_to_shopcredentials'),
        ('core', '0161_expenseentry_approved_amount_and_more'),
    ]

    operations = [
    ]
