# Generated by Django 5.2.14 on 2026-05-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_alter_trackinginfo_number'),
        ('core', '0161_add_store_name_to_shopcredentials'),
    ]

    operations = [
    ]
