# Generated by Django 5.2.14 on 2026-05-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_merge_20260531_1159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnExchangeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], db_index=True, default='return', max_length=20)),
                ('status', models.CharField(choices=[('pending_qc', 'Pending QC'), ('refund_pending', 'Refund Pending'), ('exchange_pending', 'Exchange Pending'), ('exchange_ready', 'Exchange Ready'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending_qc', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_return_exchange_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_exchange_cases', to='core.customer')),
                ('order', models.ForeignKey(help_text='The original order this return/exchange relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='return_exchange_cases', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnExchangeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added')], db_index=True, max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_exchange_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.returnexchangecase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnexchangecase',
            index=models.Index(fields=['status', '-created_at'], name='idx_rec_status_created'),
        ),
        migrations.AddIndex(
            model_name='returnexchangecase',
            index=models.Index(fields=['case_type', '-created_at'], name='idx_rec_type_created'),
        ),
    ]
