# Generated by Django 5.1.1 on 2026-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_aiagent_agentauditlog_knowledgenugget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='handover_agent_id',
            field=models.IntegerField(blank=True, help_text='ID of specific agent to assign if handover_mode is specific_agent', null=True),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='handover_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable automatic human handover'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='handover_labels',
            field=models.TextField(default='["human-needed", "ai-escalated"]', help_text='JSON list of labels to attach to conversation on handover'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='handover_mode',
            field=models.CharField(default='round_robin', help_text='Handover mode: round_robin or specific_agent', max_length=20),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='last_assigned_agent_id',
            field=models.IntegerField(blank=True, help_text='ID of the last assigned agent for round robin', null=True),
        ),
    ]
