# Generated by Django 5.2.14 on 2026-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_add_return_exchange_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='return_awb',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Courier AWB on the return parcel label (not the original dispatch AWB).', max_length=100),
        ),
    ]
