# Generated by Django 5.2.14 on 2026-05-31 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_add_return_awb_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('missing_parts', 'Missing Parts'), ('wrong_product', 'Wrong Product'), ('packaging_issue', 'Packaging Issue')], default='', help_text='Physical condition assessed during QC inspection.', max_length=30),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='qc_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when QC was completed.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='qc_completed_by',
            field=models.ForeignKey(blank=True, help_text='The user who performed QC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_completed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='qc_notes',
            field=models.TextField(blank=True, default='', help_text='Inspector notes entered during QC.'),
        ),
    ]
