# Generated by Django 5.2.14 on 2026-05-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_aiagent_handover_agent_id_aiagent_handover_enabled_and_more'),
        ('core', '0164_alter_rtoengineitem_repair_stage_choices'),
    ]

    operations = [
    ]
