# Generated by Django 5.2.14 on 2026-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_qc_fields_on_return_exchange_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='exchange_created_at',
            field=models.DateTimeField(blank=True, help_text='When the exchange order was created in Return Prime.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='exchange_exists',
            field=models.BooleanField(db_index=True, default=False, help_text='True when Return Prime has already created a replacement order for this exchange.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='exchange_meta',
            field=models.JSONField(blank=True, default=dict, help_text='JSON bag for replacement_products list and any extra exchange data.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='exchange_order_number',
            field=models.CharField(blank=True, default='', help_text='Return Prime exchange order name (e.g. #JANKI40970).', max_length=100),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='exchange_status',
            field=models.CharField(blank=True, default='', help_text='exchanged_status from Return Prime (e.g. success, pending).', max_length=50),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='replacement_order_number',
            field=models.CharField(blank=True, default='', help_text='Shopify order number for the replacement order (without #).', max_length=100),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='replacement_order_status',
            field=models.CharField(blank=True, default='', help_text='Current fulfillment/shipping status of the replacement order.', max_length=100),
        ),
    ]
