# Generated by Django 5.1.1 on 2026-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_merge_20260531_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Service Agent Config', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('response_style', models.CharField(choices=[('Concise', 'Concise'), ('Balanced', 'Balanced'), ('Detailed', 'Detailed')], default='Balanced', max_length=20)),
                ('persona', models.CharField(choices=[('default', 'Default (Professional Agent)'), ('warm', 'Warm & Encouraging'), ('calm', 'Calm & Measured'), ('genz', 'Gen Z (Casual & Energetic)'), ('aggressive', 'Aggressive (Bold & Direct)'), ('zen', 'Zen (Minimal & Mindful)')], default='default', max_length=20)),
                ('system_prompt', models.TextField(help_text='Master instructions for the deep customer service audit analysis.')),
                ('general_prompt', models.TextField(blank=True, default='', help_text='Master instructions for general conversational chat (no payload loaded).')),
                ('model_name', models.CharField(default='gemini-2.5-flash-lite', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Agent Configuration',
                'verbose_name_plural': 'Service Agent Configurations',
            },
        ),
    ]
