# Generated by Django 5.2.14 on 2026-05-31 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_exchange_metadata_on_return_exchange_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final refund amount approved by finance.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when refund was marked as completed.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_completed_by',
            field=models.ForeignKey(blank=True, help_text='The user who completed/approved the refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_completed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_notes',
            field=models.TextField(blank=True, default='', help_text='Finance processing notes for the refund.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason recorded when a refund is rejected.'),
        ),
    ]
