# Generated by Django 5.2.14 on 2026-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_refund_fields_on_return_exchange_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_screenshot',
            field=models.FileField(blank=True, help_text='Payment screenshot/receipt of the processed refund.', null=True, upload_to='refund_screenshots/'),
        ),
    ]
