# Generated by Django 5.2.14 on 2026-06-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_alter_rtoengineitem_repair_stage_choices'),
        ('core', '0168_returnexchangecase_refund_screenshot'),
    ]

    operations = [
    ]
