# Generated by Django 5.1.1 on 2026-06-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_serviceagentconfiguration'),
        ('core', '0168_returnexchangecase_refund_screenshot'),
    ]

    operations = [
    ]
