# Generated by Django 5.2.14 on 2026-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20260602_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='name',
            field=models.CharField(default='Shori', max_length=150),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are Shori, the warm, polite and exceptionally helpful AI Support Executive for our storefront. Treat customers with care.', help_text='Core guidelines and character behavior instructions for the bot'),
        ),
    ]
