# Generated by Django 5.2.14 on 2026-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_merge_20260602_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='refund_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI Refund'), ('store_credit', 'Store Credit')], default='bank_transfer', help_text='The method used to process the refund.', max_length=30),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Transaction reference code for Bank/UPI refund.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='wallet_credit_reference',
            field=models.CharField(blank=True, help_text='Store credit reference generated for future wallet integration.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnexchangeactivity',
            name='action',
            field=models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('store_credit_issued', 'Store Credit Issued'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added')], db_index=True, max_length=40),
        ),
    ]
