# Generated by Django 5.1.1 on 2026-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_alter_aiagent_name_alter_aiagent_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='gst_registration',
            field=models.CharField(blank=True, choices=[('registered', 'Registered'), ('unregistered', 'Unregistered')], default='unregistered', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='legal_business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='license_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='store_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=100),
        ),
    ]
