# Generated by Django 5.2.14 on 2026-06-02 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_returnexchangecase_refund_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='difference_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed difference: replacement price - original price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction reference code or wallet credit code for exchange settlement.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='settlement_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when settlement was finalized.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='settlement_completed_by',
            field=models.ForeignKey(blank=True, help_text='The user who finalized the exchange settlement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_exchange_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='settlement_method',
            field=models.CharField(blank=True, help_text='Method used for settlement (Refund or Payment).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='settlement_notes',
            field=models.TextField(blank=True, default='', help_text='Notes entered during settlement processing.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='settlement_type',
            field=models.CharField(blank=True, choices=[('refund_required', 'Refund Required'), ('payment_required', 'Additional Payment Required'), ('no_settlement', 'No Settlement Required')], help_text='Type of exchange settlement required.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='returnexchangeactivity',
            name='action',
            field=models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('store_credit_issued', 'Store Credit Issued'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added'), ('moved_to_exchange_settlement', 'Moved To Exchange Settlement'), ('settlement_started', 'Settlement Started'), ('refund_processed', 'Refund Difference Processed'), ('payment_collected', 'Additional Payment Collected'), ('no_settlement_req', 'No Settlement Required'), ('exchange_closed', 'Exchange Closed')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='returnexchangecase',
            name='status',
            field=models.CharField(choices=[('pending_qc', 'Pending QC'), ('refund_pending', 'Refund Pending'), ('exchange_pending', 'Exchange Pending'), ('exchange_ready', 'Exchange Ready'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('exchange_closed', 'Exchange Closed')], db_index=True, default='pending_qc', max_length=30),
        ),
    ]
