# Generated by Django 5.1.1 on 2026-06-04 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_alter_aiagent_name_alter_aiagent_system_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['org_id', 'user', 'spent_on'], name='core_exp_org_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['org_id', 'user', 'created_at'], name='core_exp_org_user_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['org_id', 'status'], name='core_exp_org_status_idx'),
        ),
    ]
