# Generated by Django 5.2.14 on 2026-06-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_returnexchangecase_difference_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnExchangeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch ID e.g., RE-20260603-01', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Processed', 'Processed')], default='Open', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Exchange Batch',
                'verbose_name_plural': 'Return Exchange Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The processing batch this return/exchange belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.returnexchangebatch'),
        ),
    ]
