# Generated by Django 5.1.1 on 2026-06-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_shopcredentials_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
    ]
