# Generated by Django 5.2.14 on 2026-06-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_returnexchangebatch_returnexchangecase_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='conversion_notes',
            field=models.TextField(blank=True, default='', help_text='Reason / notes recorded when the case was converted to an exchange.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='conversion_product_data',
            field=models.JSONField(blank=True, default=dict, help_text='Replacement product details entered during conversion (name, sku, price, variant, qty).'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the case was converted to an exchange.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='converted_by',
            field=models.ForeignKey(blank=True, help_text='The user who triggered the return-to-exchange conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_exchange_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='converted_to_exchange',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this case was originally a return that was converted to an exchange.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='courier_name',
            field=models.CharField(blank=True, default='', help_text='Courier name when customer self-ships (e.g. DTDC, Blue Dart, India Post).', max_length=100),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='manual_intake_notes',
            field=models.TextField(blank=True, default='', help_text='Notes entered during manual / self-shipped intake.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='self_shipped_tracking',
            field=models.CharField(blank=True, default='', help_text='Tracking number provided by customer for self-shipped parcel.', max_length=200),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='source',
            field=models.CharField(choices=[('return_prime', 'Return Prime'), ('self_shipped', 'Self Shipped'), ('walk_in', 'Walk-In')], db_index=True, default='return_prime', help_text='How the return arrived: via Return Prime pickup, self-shipped by customer, or walk-in.', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnexchangeactivity',
            name='action',
            field=models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('store_credit_issued', 'Store Credit Issued'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added'), ('moved_to_exchange_settlement', 'Moved To Exchange Settlement'), ('settlement_started', 'Settlement Started'), ('refund_processed', 'Refund Difference Processed'), ('payment_collected', 'Additional Payment Collected'), ('no_settlement_req', 'No Settlement Required'), ('exchange_closed', 'Exchange Closed'), ('converted_to_exchange', 'Converted To Exchange'), ('self_shipped_registered', 'Self Shipped Return Registered')], db_index=True, max_length=40),
        ),
    ]
