# Generated by Django 5.2.14 on 2026-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_source_selfshipped_conversion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangecase',
            name='customer_present',
            field=models.BooleanField(default=False, help_text='True if the customer was present at the store during intake.'),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='parcel_condition',
            field=models.CharField(blank=True, default='', help_text='Condition of the parcel upon arrival (e.g., intact, damaged).', max_length=100),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='parcel_received_date',
            field=models.DateField(blank=True, help_text='Date the parcel was received at the warehouse.', null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='received_by',
            field=models.CharField(blank=True, default='', help_text='Staff member who received the walk-in / parcel.', max_length=100),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='replacement_product',
            field=models.CharField(blank=True, default='', help_text='Replacement product name for manual intake exchange cases.', max_length=255),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='replacement_product_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Replacement product value for manual intake exchange cases.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnexchangecase',
            name='store_location',
            field=models.CharField(blank=True, default='', help_text='Store location for walk-in cases.', max_length=100),
        ),
        migrations.AlterField(
            model_name='returnexchangeactivity',
            name='action',
            field=models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('store_credit_issued', 'Store Credit Issued'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added'), ('moved_to_exchange_settlement', 'Moved To Exchange Settlement'), ('settlement_started', 'Settlement Started'), ('refund_processed', 'Refund Difference Processed'), ('payment_collected', 'Additional Payment Collected'), ('no_settlement_req', 'No Settlement Required'), ('exchange_closed', 'Exchange Closed'), ('converted_to_exchange', 'Converted To Exchange'), ('self_shipped_registered', 'Self Shipped Return Registered'), ('self_shipped_case_created', 'Self Shipped Case Created'), ('courier_registered', 'Courier Registered'), ('parcel_received', 'Parcel Received'), ('self_shipped_exchange_created', 'Self Shipped Exchange Created'), ('replacement_product_selected', 'Replacement Product Selected'), ('walk_in_return_registered', 'Walk In Return Registered'), ('received_at_store', 'Received At Store'), ('walk_in_exchange_registered', 'Walk In Exchange Registered')], db_index=True, max_length=40),
        ),
    ]
