# Generated by Django 5.2.14 on 2026-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_thorfinnchatsession_thorfinnchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='task_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='task_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
