# Generated by Django 5.2.14 on 2026-06-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_expense_composite_indexes'),
        ('core', '0174_alter_chatmessage_attachment_mime_type_and_more'),
        ('core', '0174_returnexchangecase_customer_present_and_more'),
    ]

    operations = [
    ]
