# Generated by Django 5.1.1 on 2026-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_alter_chatmessage_attachment_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierratecard',
            name='efss_surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Elevated Freight Stability Surcharge % (e.g. 5.0 or 7.0)', max_digits=5),
        ),
    ]
