# Generated by Django 5.1.1 on 2026-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_courierratecard_efss_surcharge_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierratecard',
            name='caf_mode',
            field=models.CharField(choices=[('STATIC', 'Static Percent'), ('DYNAMIC_OFF_MECHANISM', 'Dynamic off Mechanism')], default='STATIC', max_length=30),
        ),
        migrations.AddField(
            model_name='courierratecard',
            name='caf_offset',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage to deduct from mechanism CAF (e.g., 5.0 for mechanism - 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='courierratecard',
            name='caf_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carrier Adjustment Factor (CAF) % added on base freight (e.g., 10.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='courierratecard',
            name='fuel_surcharge_mode',
            field=models.CharField(choices=[('STATIC', 'Static Percent'), ('DYNAMIC_OFF_MECHANISM', 'Dynamic off Mechanism')], default='STATIC', max_length=30),
        ),
        migrations.AddField(
            model_name='courierratecard',
            name='fuel_surcharge_offset',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage to deduct from mechanism fuel surcharge (e.g., 30.0 for mechanism - 30%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='CourierSurchargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_partner', models.CharField(db_index=True, default='Bluedart', help_text="e.g. 'Bluedart'", max_length=50)),
                ('month_date', models.DateField(help_text='First day of the month (e.g., 2026-04-01) for this surcharge cycle')),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, default=0, help_text='Official/mechanism Fuel Surcharge percentage', max_digits=5)),
                ('caf_percent', models.DecimalField(decimal_places=2, default=0, help_text='Official/mechanism Currency Adjustment Factor percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_date'],
                'unique_together': {('org_id', 'courier_partner', 'month_date')},
            },
        ),
    ]
