# Generated by Django 5.2.14 on 2026-06-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_merge_20260604_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
