# Generated by Django 5.1.1 on 2026-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_courierratecard_caf_mode_courierratecard_caf_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_awb',
            field=models.CharField(blank=True, default='', help_text='AWB of the exchange delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_shipping_company',
            field=models.CharField(blank=True, default='', help_text='Shipping carrier for exchange', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='return_awb',
            field=models.CharField(blank=True, default='', help_text='AWB of the returned items', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='return_shipping_company',
            field=models.CharField(blank=True, default='', help_text='Shipping carrier for returns', max_length=100),
        ),
    ]
