# Generated by Django 5.1.1 on 2026-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_order_exchange_awb_order_exchange_shipping_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierinvoiceline',
            name='shipment_type',
            field=models.CharField(choices=[('Forward', 'Forward Delivery'), ('RTO', 'Return to Origin (RTO)'), ('Return', 'Customer Return'), ('Exchange', 'Exchange'), ('Credit', 'Credit / Adjustment')], db_index=True, default='Forward', max_length=20),
        ),
    ]
