# Generated by Django 5.1.1 on 2026-06-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_returnrequest_request_number'),
        ('core', '0178_alter_courierinvoiceline_shipment_type'),
    ]

    operations = [
    ]
