# Generated by Django 5.1.1 on 2026-06-06 05:12

from django.db import migrations, models


def backfill_product_types(apps, schema_editor):
    from django.db.models import Q
    FreightInvoice = apps.get_model('core', 'FreightInvoice')
    for inv in FreightInvoice.objects.all():
        cod_count = inv.lines.filter(shipment__payment_type__in=['COD', 'Partially Paid']).count()
        matched_count = inv.lines.exclude(shipment=None).count()
        if matched_count > 0:
            inv.product_type = 'COD' if (cod_count / matched_count > 0.5) else 'Prepaid'
        else:
            # Fallback
            cod_code_count = inv.lines.filter(Q(product_code__icontains='C') | Q(product_code__icontains='COD')).count()
            total_count = inv.lines.count()
            inv.product_type = 'COD' if (total_count > 0 and cod_code_count / total_count > 0.5) else 'Prepaid'
        inv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_merge_20260605_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightinvoice',
            name='product_type',
            field=models.CharField(blank=True, default='', help_text='Invoice classification (COD or Prepaid)', max_length=50),
        ),
        migrations.RunPython(backfill_product_types),
    ]
