# Generated by Django 5.1.1 on 2026-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_freightinvoice_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierZoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_partner', models.CharField(db_index=True, default='Bluedart', max_length=50)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('zone_code', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bluedart Zone Mapping',
                'verbose_name_plural': 'Bluedart Zone Mappings',
                'unique_together': {('org_id', 'courier_partner', 'pincode')},
            },
        ),
    ]
