# Generated by Django 5.2.14 on 2026-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_courierzonemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangebatch',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, help_text='The organization this batch belongs to.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rtobatch',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, help_text='The organization this batch belongs to.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returnexchangeactivity',
            name='action',
            field=models.CharField(choices=[('parcel_scanned', 'Parcel Scanned'), ('moved_to_qc', 'Moved To QC'), ('qc_passed', 'QC Passed'), ('qc_failed', 'QC Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('store_credit_issued', 'Store Credit Issued'), ('exchange_initiated', 'Exchange Initiated'), ('settlement_completed', 'Settlement Completed'), ('dispatched', 'Dispatched'), ('rejected', 'Rejected'), ('note_added', 'Note Added'), ('moved_to_exchange_settlement', 'Moved To Exchange Settlement'), ('settlement_started', 'Settlement Started'), ('refund_processed', 'Refund Difference Processed'), ('payment_collected', 'Additional Payment Collected'), ('no_settlement_req', 'No Settlement Required'), ('exchange_closed', 'Exchange Closed'), ('converted_to_exchange', 'Converted To Exchange'), ('self_shipped_registered', 'Self Shipped Return Registered'), ('self_shipped_case_created', 'Self Shipped Case Created'), ('courier_registered', 'Courier Registered'), ('parcel_received', 'Parcel Received'), ('self_shipped_exchange_created', 'Self Shipped Exchange Created'), ('replacement_product_selected', 'Replacement Product Selected'), ('walk_in_return_registered', 'Walk In Return Registered'), ('received_at_store', 'Received At Store'), ('walk_in_exchange_registered', 'Walk In Exchange Registered'), ('exchange_creation_started', 'Exchange Creation Started'), ('exchange_order_generated', 'Exchange Order Generated'), ('shopify_order_created', 'Shopify Order Created'), ('return_prime_updated', 'Return Prime Updated'), ('exchange_created_successfully', 'Exchange Created Successfully')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='returnexchangebatch',
            name='name',
            field=models.CharField(help_text='Batch ID e.g., RE-20260603-01', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='returnexchangebatch',
            unique_together={('org_id', 'name')},
        ),
    ]
