# Generated by Django 5.1.1 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_courierzonemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceline',
            name='anomaly_category',
            field=models.CharField(blank=True, choices=[('exact_match', 'Exact Match'), ('minor_rounding', 'Minor Rounding Difference'), ('surcharge_mismatch', 'Surcharge Mismatch (FS/CAF)'), ('weight_slab_mismatch', 'Weight Slab Mismatch'), ('cod_mismatch', 'COD Calculation Mismatch'), ('duplicate_charge', 'Duplicate Charge Suspected'), ('unknown_pricing', 'Unknown Pricing')], db_index=True, default='', help_text='Granular anomaly classification', max_length=30),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='billing_layer',
            field=models.CharField(blank=True, choices=[('excel', 'Excel (decomposable components)'), ('pdf', 'PDF (merged charges)'), ('credit', 'Credit / Adjustment')], default='excel', help_text='Which billing layer this line was parsed from', max_length=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='Confidence score (0-100) based on formula match, history, and consistency'),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='efss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='EFSS — Elevated Freight Stability Surcharge (freight × efss%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='expected_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected Excel net amount = freight + cod + efss + fs + caf', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courierinvoiceline',
            name='expected_pdf_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected PDF amount = freight + cod + efss', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BillingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_partner', models.CharField(db_index=True, default='Bluedart', max_length=50)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('zone', models.CharField(blank=True, max_length=20)),
                ('weight_slab', models.DecimalField(decimal_places=2, default=0.5, help_text='Charged weight slab in KG', max_digits=6)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total billed amount observed for this pattern', max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_type', models.CharField(blank=True, max_length=20)),
                ('occurrence_count', models.IntegerField(default=1, help_text='How many times this exact pattern has been seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurrence_count'],
                'indexes': [models.Index(fields=['org_id', 'courier_partner', 'city'], name='idx_billingpat_city'), models.Index(fields=['org_id', 'courier_partner', 'pincode'], name='idx_billingpat_pin')],
                'unique_together': {('org_id', 'courier_partner', 'pincode', 'zone', 'weight_slab', 'billed_amount')},
            },
        ),
    ]
