# Generated by Django 5.2.14 on 2026-06-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_courierinvoiceline_anomaly_category_and_more'),
        ('core', '0182_returnexchangebatch_org_id_rtobatch_org_id_and_more'),
    ]

    operations = [
    ]
