# Generated by Django 5.1.1 on 2026-06-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_merge_0183_chat_rooms_0183_merge_20260608_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courierzonemapping',
            name='hub_name',
            field=models.CharField(blank=True, help_text="Official courier hub name serving this pincode (e.g., 'Jaipur Hub', 'Delhi NCR Hub'). Populated when courier shares hub-level mapping. Used by Hub Analytics.", max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transit_hub',
            field=models.CharField(blank=True, default='', help_text="Courier hub name serving this shipment (e.g., 'Jaipur Hub'). Populated via pincode lookup.", max_length=200),
        ),
        migrations.CreateModel(
            name='CourierSLAContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_partner', models.CharField(db_index=True, max_length=50)),
                ('zone', models.CharField(choices=[('Local', 'Local'), ('Intra-City', 'Intra-City'), ('Within State', 'Within State'), ('Regional', 'Regional'), ('Metro', 'Metro-to-Metro'), ('National', 'National'), ('Special', 'Special / Remote')], max_length=20)),
                ('shipping_mode', models.CharField(choices=[('Surface', 'Surface'), ('Air', 'Air'), ('Apex', 'Apex / Air Express')], default='Surface', max_length=10)),
                ('promised_days', models.IntegerField(help_text='SLA: delivery within N business days')),
                ('penalty_per_day', models.DecimalField(decimal_places=2, default=0, help_text='Penalty owed per day of SLA breach (₹). 0 = no penalty clause.', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional: Contract reference, agreement date, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['courier_partner', 'zone'],
                'unique_together': {('org_id', 'courier_partner', 'zone', 'shipping_mode')},
            },
        ),
        migrations.CreateModel(
            name='CustomerRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('customer_phone', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_email', models.CharField(blank=True, default='', max_length=200)),
                ('total_orders', models.IntegerField(default=0)),
                ('rto_count', models.IntegerField(default=0)),
                ('delivery_success_count', models.IntegerField(default=0)),
                ('cod_order_count', models.IntegerField(default=0)),
                ('refusal_count', models.IntegerField(default=0, help_text="Orders where ndr_call_status contains 'Refused' or 'Cancel'")),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('risk_score', models.IntegerField(db_index=True, default=0, help_text='0-100. Higher = riskier. Computed from rto/refusal/cod/delivery rates.')),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk (0-30)'), ('Medium', 'Medium Risk (31-60)'), ('High', 'High Risk (61-85)'), ('Blocked', 'Blocked (86-100)')], db_index=True, default='Low', max_length=10)),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='e.g. ["OTP Verification", "Manual Call Verification", "Require Prepaid"]')),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['org_id', 'risk_level', '-risk_score'], name='idx_crp_org_risk'), models.Index(fields=['org_id', '-risk_score'], name='idx_crp_org_score')],
                'unique_together': {('org_id', 'customer_phone')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('exception_type', models.CharField(choices=[('Lost', 'Lost Shipment'), ('Damaged', 'Damaged Shipment'), ('Delayed', 'Delayed Shipment'), ('MissingScan', 'Missing Scan (>3 days no update)'), ('WrongDelivery', 'Wrong Delivery'), ('WeightDispute', 'Weight Dispute'), ('FraudAlert', 'Fraud Alert'), ('Other', 'Other')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InvestigationPending', 'Courier Investigation Pending'), ('ResolutionPending', 'Resolution Pending'), ('ClaimRecovery', 'Claim Recovery'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], db_index=True, default='Open', max_length=25)),
                ('description', models.TextField(blank=True, help_text='Details of the exception (auto-filled for auto-detected, manual for agent-created)')),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount claimed from courier (₹)', max_digits=10)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually recovered (₹)', max_digits=10)),
                ('notes', models.TextField(blank=True, default='', help_text='Agent notes on investigation progress')),
                ('is_auto_detected', models.BooleanField(default=False, help_text='True if created by the auto-detection Celery task')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the exception was closed or rejected', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Agent responsible for investigating/resolving this exception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipment_exceptions', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.shipment')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['org_id', 'status', '-detected_at'], name='idx_exc_org_status'), models.Index(fields=['org_id', 'exception_type'], name='idx_exc_org_type'), models.Index(fields=['org_id', 'is_auto_detected'], name='idx_exc_org_auto')],
            },
        ),
    ]
