# Generated by Django 5.1.1 on 2026-06-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_chat_rooms'),
        ('core', '0183_merge_20260608_1524'),
    ]

    operations = [
    ]
