# Generated by Django 5.1.1 on 2026-06-09 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_merge_0183_chat_rooms_0183_merge_20260608_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='last_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='last_reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_replied_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_replies', to='core.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread_reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessagemention',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessagemention',
            name='mention_type',
            field=models.CharField(choices=[('user', 'User'), ('team', 'Team'), ('channel', 'Channel'), ('everyone', 'Everyone')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('channel_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_channels', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatchannel'),
        ),
        migrations.CreateModel(
            name='ChatChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.chatchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chatchannel',
            index=models.Index(fields=['workspace', 'is_archived'], name='chatchannel_ws_arch_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatchannel',
            unique_together={('workspace', 'name')},
        ),
        migrations.AddIndex(
            model_name='chatchannelmember',
            index=models.Index(fields=['channel', 'role'], name='chatchanmem_chan_role_idx'),
        ),
        migrations.AddIndex(
            model_name='chatchannelmember',
            index=models.Index(fields=['user', 'role'], name='chatchanmem_user_role_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatchannelmember',
            unique_together={('channel', 'user')},
        ),
    ]
