# Generated by Django 5.1.1 on 2026-06-09 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0184_add_logistics_enterprise_gaps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRiskScore',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='risk_score_detail', serialize=False, to='core.shipment')),
                ('risk_score', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('horizon_24h', models.BooleanField(default=False)),
                ('horizon_48h', models.BooleanField(default=False)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('predicted_delay', models.BooleanField(default=False)),
                ('actual_delayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControlTowerActionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('awbs', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourierHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(db_index=True, max_length=50)),
                ('score_date', models.DateField(db_index=True)),
                ('composite_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sla_adherence_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ndr_rate_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_delay_hrs', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('scan_quality_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dispute_rate_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
            ],
            options={
                'ordering': ['-score_date', 'courier_id'],
                'unique_together': {('courier_id', 'score_date')},
            },
        ),
        migrations.CreateModel(
            name='PenaltyTicket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('courier_id', models.CharField(db_index=True, max_length=50)),
                ('sla_deadline', models.DateTimeField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('breach_days', models.IntegerField(default=0)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('recovered', 'Recovered'), ('disputed', 'Disputed')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='core.courierslacontract')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_tickets', to='core.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
