# Generated by Django 5.1.1 on 2026-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_shipmentriskscore_controltoweractionauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('alert_type', models.CharField(blank=True, default='', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
