# Generated by Django 5.1.1 on 2026-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_chatmessage_last_reply_at_chatmessage_last_reply_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='can_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='can_react',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='can_upload',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='everyone_allowed',
            field=models.CharField(default='admins', max_length=20),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='show_in_directory',
            field=models.BooleanField(default=True),
        ),
    ]
