# Generated by Django 5.1.7 on 2026-06-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_crmactivity_crmattachment_crmnote_crmtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('create_activity', 'Create Activity'), ('assign_user', 'Assign User'), ('change_status', 'Change Status'), ('send_notification', 'Send In-App Notification')], max_length=50)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Action parameters (e.g. title, description, assignee_id, status_val)')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('days_since_activity', 'Days Since Activity')], max_length=50)),
                ('value', models.TextField(help_text='Value to compare against.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.workflow')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('company', 'Company'), ('quote', 'Quote'), ('customer', 'Customer'), ('task', 'Task')], max_length=50)),
                ('trigger_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('task_overdue', 'Task Overdue'), ('quote_accepted', 'Quote Accepted'), ('lead_assigned', 'Lead Assigned')], max_length=50)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='core.workflow')),
            ],
        ),
    ]
