# Generated by Django 5.1.1 on 2026-06-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_chatchannel_can_invite_chatchannel_can_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPresence',
        ),
    ]
