# Generated by Django 5.1.1 on 2026-06-10 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_weatheralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['org_id', 'order_number'], name='idx_ord_org_ordernum'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['org_id', 'status', 'internal_fulfillment_status'], name='idx_ord_org_stat_ifs'),
        ),
    ]
