# Generated by Django 5.1.1 on 2026-06-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_add_order_number_index_and_compound_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ndr_classification_confidence',
            field=models.IntegerField(default=0, help_text='AI classification confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_conversion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('RTO', 'RTO')], db_index=True, default='PENDING', help_text='Funnel conversion status of this NDR', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_last_scan_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last tracking event', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_reason_category',
            field=models.CharField(blank=True, db_index=True, help_text='Gemini-classified reason category for delivery failure', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ndr_rto_risk_score',
            field=models.IntegerField(db_index=True, default=0, help_text='RTO probability score from 0-100 calculated by RTO Scorer'),
        ),
    ]
