# Generated by Django 5.1.7 on 2026-06-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_workflow_workflowaction_workflowcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stale_lead', 'Stale Lead'), ('expiring_quote', 'Expiring Quote'), ('overdue_task', 'Overdue Task'), ('inactive_company', 'Inactive Company'), ('high_value_opportunity', 'High Value Opportunity'), ('revenue_decline', 'Revenue Decline')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(help_text='e.g. lead, company, quote, customer, task', max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('score', models.FloatField(default=0.0, help_text='Priority rank weight score')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='core_recomm_shop_id_298898_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_recomm_entity__3c3094_idx'), models.Index(fields=['type'], name='core_recomm_type_8af306_idx')],
            },
        ),
    ]
