# Generated by Django 5.1.1 on 2026-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_delete_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('documents', 'Documents'), ('audio', 'Audio'), ('archives', 'Archives'), ('shared_files', 'Shared Files')], db_index=True, default='shared_files', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='chat_context_name',
            field=models.CharField(blank=True, default='', help_text='Room / channel / conversation name', max_length=255),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='chat_message_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='chat_sender_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='chat_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='source',
            field=models.CharField(choices=[('upload', 'Direct Upload'), ('my_chats', 'MyChats')], db_index=True, default='upload', max_length=20),
        ),
    ]
