# Generated by Django 5.1.1 on 2026-06-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_vault_chat_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='vault_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='core.galleryitem'),
        ),
    ]
