# Generated by Django 5.1.1 on 2026-06-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_order_ndr_classification_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierzonemapping',
            name='hub_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courierzonemapping',
            name='hub_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courierzonemapping',
            name='pincode_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='courierzonemapping',
            name='pincode_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='NDRFraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('SCAN_GAP', 'Impossible scan-to-attempt time gap'), ('LOCATION_MISMATCH', 'Geographic coordinates mismatch (Fake Attempt)'), ('DUPLICATE_ATTEMPT', 'Duplicate attempt back-to-back')], db_index=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed analysis proving physical impossibility')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='core.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NDRPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('reason_category', models.CharField(choices=[('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('ADDRESS_ISSUE', 'Address Issue'), ('REFUSED_DELIVERY', 'Refused Delivery'), ('PREMISES_CLOSED', 'Premises Closed'), ('COD_NOT_READY', 'COD Not Ready'), ('OTHERS', 'Others')], db_index=True, max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority playbooks are run first')),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON describing matching conditions, e.g. {"min_value": 1000}')),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of step actions to execute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('org_id', 'reason_category', 'priority')},
            },
        ),
    ]
