# Generated by Django 5.1.1 on 2026-06-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_courierzonemapping_hub_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='chatwoot_api_key_encrypted',
            field=models.CharField(blank=True, help_text='Encrypted API token/key for Chatwoot', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='chatwoot_endpoint',
            field=models.CharField(blank=True, help_text='Webhook or API endpoint for Chatwoot outbound integration', max_length=500, null=True),
        ),
    ]
