# Generated by Django 5.1.1 on 2026-06-12 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_localcalendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localcalendarevent',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='chatpinnedmessage',
            name='chatpin_room_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chatpinnedmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatpinnedmessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='core.chatchannel'),
        ),
        migrations.AlterField(
            model_name='chatpinnedmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='core.chatroom'),
        ),
        migrations.AddConstraint(
            model_name='chatpinnedmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'message'), name='unique_room_message_pin'),
        ),
        migrations.AddConstraint(
            model_name='chatpinnedmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('channel', 'message'), name='unique_channel_message_pin'),
        ),
        migrations.DeleteModel(
            name='LocalCalendarEvent',
        ),
    ]
