# Generated by Django 5.1.1 on 2026-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_shopcredentials_chatwoot_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_auto_confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='True if confirmed automatically by the AI agent, False if confirmed manually by a user.'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_test_order',
            field=models.BooleanField(db_index=True, default=False, help_text='Explicitly marked as a test order. Excluded from auto-confirmation and picklist generation.'),
        ),
        migrations.AddField(
            model_name='order',
            name='picklist_generated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this order was last exported/sent in a picklist email.', null=True),
        ),
        migrations.AddField(
            model_name='teammembersettings',
            name='subscribe_picklist_email',
            field=models.BooleanField(default=False, help_text='Whether this team member receives daily morning picklist emails.'),
        ),
    ]
