# Generated by Django 5.1.7 on 2026-06-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_notification_notificationdeliverylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='Month of the quota (1-12)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotas', to='core.shopcredentials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop', 'user', 'year', 'month')},
            },
        ),
    ]
