# Generated by Django 5.1.1 on 2026-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_remove_localcalendarevent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydesknote',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
