# Generated by Django 5.1.1 on 2026-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_order_is_auto_confirmed_order_is_test_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerriskprofile',
            name='blocked_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by the operator when manually blocking this customer.'),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='is_manually_blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually blocked by an operator. Overrides computed risk_level.'),
        ),
        migrations.AddField(
            model_name='shipmentexception',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of status-change events. Each entry: {timestamp, actor, from_status, to_status, notes, recovered_amount}'),
        ),
    ]
