# Generated by Django 5.1.7 on 2026-06-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_salesquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Wholesale Lead'), ('company', 'Company / Retail Store'), ('quote', 'Quotation')], max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('risk_score', models.IntegerField(default=0, help_text='Calculated risk score from 0 (low) to 100 (critical)')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Identified risk reasons')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_risks', to='core.shopcredentials')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'risk_score'], name='core_dealri_shop_id_dbe7dc_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_dealri_entity__f65e00_idx')],
                'unique_together': {('shop', 'entity_type', 'entity_id')},
            },
        ),
    ]
