# Generated by Django 5.1.7 on 2026-06-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0192_dealrisk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('health_score', models.IntegerField(default=100, help_text='Overall health score (0-100)')),
                ('engagement_score', models.IntegerField(default=100, help_text='Engagement rating (0-100)')),
                ('support_ticket_count', models.IntegerField(default=0, help_text='Number of unresolved support tickets')),
                ('churn_risk', models.CharField(choices=[('low', 'Low Churn Risk'), ('medium', 'Medium Churn Risk'), ('high', 'High Churn Risk'), ('critical', 'Critical Churn Risk')], default='low', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Detailed engagement metrics')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_health_scores', to='core.shopcredentials')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_custom_content_195b33_idx'), models.Index(fields=['shop', 'health_score'], name='core_custom_shop_id_980a0c_idx')],
                'unique_together': {('shop', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='RenewalTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('annual_recurring_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('upsell_opportunity_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_negotiation', 'In Negotiation'), ('renewed', 'Renewed'), ('churned', 'Churned'), ('suspended', 'Suspended')], default='active', max_length=25)),
                ('renewal_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_trackers', to='core.shopcredentials')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_renewa_content_2d2527_idx'), models.Index(fields=['shop', 'contract_end_date'], name='core_renewa_shop_id_bee3f8_idx')],
                'unique_together': {('shop', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='SuccessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('onboarding', 'Onboarding Step'), ('check_in', 'Scheduled Check-in'), ('renewal', 'Renewal Preparation'), ('escalation', 'Escalation / Save Playbook')], default='onboarding', max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_success_tasks', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_tasks', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_succes_content_9c4968_idx'), models.Index(fields=['shop', 'status'], name='core_succes_shop_id_c4c49a_idx')],
            },
        ),
    ]
