# Generated by Django 5.1.1 on 2026-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_mydesknote_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiednotification',
            name='module',
            field=models.CharField(choices=[('postits', 'PostIts'), ('notes', 'My Notes'), ('tasks', 'Tasks'), ('my_chats', 'My Chats'), ('expenses', 'Expenses'), ('leave_requests', 'Leave Requests'), ('gallery', 'Gallery'), ('my_meetings', 'My Meetings'), ('training', 'Training')], max_length=40),
        ),
    ]
