# Generated by Django 5.1.1 on 2026-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_add_exception_audit_trail_and_customer_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='awb_error',
            field=models.TextField(blank=True, default='', help_text='Error message if auto AWB generation/booking failed'),
        ),
    ]
