# Generated by Django 5.1.1 on 2026-06-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_order_awb_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_box_breadth',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_box_height',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_box_length',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_fallback_carrier_id',
            field=models.CharField(blank=True, default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_fallback_carrier_title',
            field=models.CharField(blank=True, default='Direct Delhivery', max_length=100),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_invoice_number_prefix',
            field=models.CharField(blank=True, default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_order_weight',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_primary_carrier_id',
            field=models.CharField(blank=True, default='82600', max_length=50),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_primary_carrier_title',
            field=models.CharField(blank=True, default='Bluedart Direct - Surface', max_length=100),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_return_warehouse_id',
            field=models.IntegerField(blank=True, default=39842, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_warehouse_id',
            field=models.IntegerField(blank=True, default=39842, null=True),
        ),
    ]
