# Generated by Django 5.1.7 on 2026-06-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0193_customerhealthscore_renewaltracker_successtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='core.shopcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, help_text='Internet Message-ID RFC 2822', max_length=255, null=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('cc', models.TextField(blank=True, help_text='Comma separated CC addresses')),
                ('bcc', models.TextField(blank=True, help_text='Comma separated BCC addresses')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Body content, max 65535 characters')),
                ('sent_at', models.DateTimeField()),
                ('is_incoming', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.emailthread')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['content_type', 'object_id'], name='core_emailt_content_4dc6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['shop', 'last_message_at'], name='core_emailt_shop_id_231f08_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['thread', 'sent_at'], name='core_emailm_thread__089c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_id'], name='core_emailm_message_f619ee_idx'),
        ),
    ]
