# Generated by Django 5.1.1 on 2026-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_shopcredentials_shipway_box_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='shipway_store_code',
            field=models.IntegerField(blank=True, default=44180, null=True),
        ),
    ]
