# Generated by Django 5.1.1 on 2026-06-16 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_chatcommunity_chatchannel_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcommunity',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='channel_type',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('admin', 'Admin'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatCommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.chatcommunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['community', 'role'], name='chatcommmem_comm_role_idx'), models.Index(fields=['user', 'role'], name='chatcommmem_user_role_idx')],
                'unique_together': {('community', 'user')},
            },
        ),
    ]
