# Generated by Django 5.1.1 on 2026-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_shopcredentials_shipway_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierratecard',
            name='reverse_pickup_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat reverse pickup / To Pay charges per AWB for returns/exchanges (₹)', max_digits=8),
        ),
    ]
