# Generated by Django 5.1.7 on 2026-06-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_savedfilter_systemauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField(help_text='Newline separated list of allowed redirect URIs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_apps', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('secret_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('target_url', models.URLField(max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_webhook_logs', to='core.shopcredentials')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('connection_type', models.CharField(default='oauth', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('credentials_json', models.JSONField(blank=True, default=dict, help_text='OAuth tokens or API key configurations')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='core.shopcredentials')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('shop', 'provider')},
            },
        ),
        migrations.AddIndex(
            model_name='webhooksubscription',
            index=models.Index(fields=['shop', 'event_type', 'is_active'], name='core_webhoo_shop_id_fd2007_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwebhooklog',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='core_outbou_shop_id_454f4a_idx'),
        ),
    ]
