# Generated by Django 5.1.1 on 2026-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_courierratecard_reverse_pickup_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
