# Generated by Django 5.1.7 on 2026-06-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_oauthapp_webhooksubscription_outboundwebhooklog_and_more'),
        ('core', '0197_customer_total_spent'),
    ]

    operations = [
    ]
