# Generated by Django 5.1.1 on 2026-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_customer_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='shipping_platform',
            field=models.CharField(choices=[('shipway', 'Shipway'), ('shiprocket', 'Shiprocket')], default='shipway', help_text='Select active shipping/AWB generation provider platform', max_length=20),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_email_encrypted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_password_encrypted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_pickup_location',
            field=models.CharField(blank=True, default='', help_text='Nickname of pickup address in Shiprocket', max_length=150),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
