# Generated by Django 5.1.1 on 2026-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_shopcredentials_shipping_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_box_breadth',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_box_height',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_box_length',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='shiprocket_order_weight',
            field=models.FloatField(blank=True, default=0.5, help_text='Default shipment weight in Kilograms (e.g. 0.5 for 500g)', null=True),
        ),
    ]
