# Generated by Django 5.1.1 on 2026-06-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_shopcredentials_shiprocket_box_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='skip_shipway_pii_sync',
            field=models.BooleanField(default=False, help_text='Skip fetching customer PII from Shipway (enable if Shopify app has native PII access)'),
        ),
    ]
