# Generated by Django 5.1.1 on 2026-06-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_alter_unifiednotification_module'),
        ('core', '0196_oauthapp_webhooksubscription_outboundwebhooklog_and_more'),
        ('core', '0200_shopcredentials_skip_shipway_pii_sync'),
    ]

    operations = [
    ]
