# Generated by Django 5.1.1 on 2026-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='enable_auto_assign_couriers',
            field=models.BooleanField(default=True, help_text='Automatically assign couriers / book AWB for confirmed orders'),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='enable_auto_confirm_orders',
            field=models.BooleanField(default=True, help_text='Automatically confirm eligible orders based on AI risk evaluation'),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='enable_auto_send_picklists',
            field=models.BooleanField(default=True, help_text='Automatically compile and send morning picklist reports via email'),
        ),
    ]
