# Generated by Django 5.1.1 on 2026-06-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_gmail_auth'),
        ('core', '0198_merge_20260615_1306'),
        ('core', '0203_shopcredentials_enable_auto_assign_couriers_and_more'),
    ]

    operations = [
    ]
