# Generated by Django 5.2.15 on 2026-06-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_chatcommunity_is_public_and_more'),
        ('core', '0204_merge_20260615_1802'),
    ]

    operations = [
    ]
