# Generated by Django 5.1.1 on 2026-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0204_merge_20260615_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_reason',
            field=models.CharField(blank=True, help_text='Why the AI auto-confirmed this order.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Why the AI placed the order on hold.', max_length=255, null=True),
        ),
    ]
