# Generated by Django 5.2.15 on 2026-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_merge_20260617_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('sales_overview', 'Sales Overview'), ('order_attribution', 'Order Attribution'), ('performance_analytics', 'Performance Analytics'), ('sales_forecasting', 'Sales Forecasting'), ('retail_crm_leads', 'Retail CRM & Leads'), ('quotation_tracker', 'Quotation Tracker'), ('cart_recovery', 'Cart Recovery'), ('shopify_analytics', 'Shopify Analytics'), ('marketplace', 'Marketplace'), ('operations', 'Operations'), ('logistics', 'Logistics'), ('rto_engine', 'RTO Engine'), ('customer_care', 'Customer Care'), ('intelligence', 'Intelligence'), ('product_merchandising', 'Product & Merchandising'), ('marketing', 'Marketing'), ('finance_accounting', 'Finance & Accounting')], default='sales_overview', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('sales_overview', 'Sales Overview'), ('order_attribution', 'Order Attribution'), ('performance_analytics', 'Performance Analytics'), ('sales_forecasting', 'Sales Forecasting'), ('retail_crm_leads', 'Retail CRM & Leads'), ('quotation_tracker', 'Quotation Tracker'), ('cart_recovery', 'Cart Recovery'), ('shopify_analytics', 'Shopify Analytics'), ('marketplace', 'Marketplace'), ('operations', 'Operations'), ('logistics', 'Logistics'), ('rto_engine', 'RTO Engine'), ('customer_care', 'Customer Care'), ('intelligence', 'Intelligence'), ('product_merchandising', 'Product & Merchandising'), ('marketing', 'Marketing'), ('finance_accounting', 'Finance & Accounting')], max_length=50),
        ),
    ]
