# Generated by Django 5.1.1 on 2026-06-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_order_confirmation_reason_order_hold_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(help_text="e.g. 'HQ', 'Warehouse', 'Mumbai Branch'", max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geofence_radius_meters', models.PositiveIntegerField(default=200, help_text='Radius in meters within which an employee is considered WFO')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('label', models.CharField(blank=True, default='', help_text="e.g. 'Main ISP', 'Backup Line', 'WiFi'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_ips', to='core.officelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('logout_source', models.CharField(blank=True, choices=[('manual', 'Manual Logout'), ('midnight_job', 'Midnight Auto-Logout'), ('idle', 'Idle Timeout'), ('page_unload', 'Page Unload')], default='', max_length=20)),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('login_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('gps_status', models.CharField(choices=[('captured', 'Captured'), ('denied', 'Permission Denied'), ('unavailable', 'Unavailable'), ('timeout', 'Timeout'), ('error', 'Error')], default='unavailable', max_length=20)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('gps_distance_meters', models.FloatField(blank=True, help_text='Distance in meters from the nearest office', null=True)),
                ('work_mode', models.CharField(choices=[('wfo', 'Work From Office'), ('wfh', 'Work From Home'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('work_mode_reason', models.CharField(blank=True, default='', help_text="e.g. 'ip_match', 'gps_within_geofence', 'no_match'", max_length=100)),
                ('is_anomalous', models.BooleanField(db_index=True, default=False)),
                ('anomaly_reasons', models.JSONField(blank=True, default=list)),
                ('anomaly_resolution', models.CharField(choices=[('unresolved', 'Unresolved'), ('ok', 'Marked OK'), ('suspicious', 'Confirmed Suspicious'), ('dismissed', 'Dismissed')], default='unresolved', max_length=20)),
                ('anomaly_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly_resolution_note', models.TextField(blank=True, default='')),
                ('anomaly_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('gps_nearest_office', models.ForeignKey(blank=True, help_text='Nearest office by GPS distance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.officelocation')),
                ('ip_matched_office', models.ForeignKey(blank=True, help_text='Office whose registered IP matched the login IP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.officelocation')),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='officelocation',
            index=models.Index(fields=['org_id', 'is_active'], name='core_offloc_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='officeip',
            constraint=models.UniqueConstraint(fields=('office', 'ip_address'), name='uniq_office_ip'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['org_id', 'user', 'login_at'], name='attsess_org_usr_login_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['org_id', 'login_at'], name='attsess_org_login_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['org_id', 'is_anomalous', 'anomaly_resolution'], name='attsess_org_anomaly_idx'),
        ),
    ]
