# Generated by Django 5.1.1 on 2026-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_officelocation_officeip_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='idle_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Inactivity time limit in minutes before alerting the user'),
        ),
    ]
