# Generated by Django 5.2.15 on 2026-06-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_notification_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('sales_overview', 'sales_overview'), ('order_attribution', 'order_attribution'), ('performance_analytics', 'performance_analytics'), ('sales_forecasting', 'sales_forecasting'), ('retail_crm_leads', 'retail_crm_leads'), ('quotation_tracker', 'quotation_tracker'), ('cart_recovery', 'cart_recovery'), ('shopify_analytics', 'shopify_analytics'), ('marketplace', 'marketplace'), ('operations', 'operations'), ('logistics', 'logistics'), ('rto_engine', 'rto_engine'), ('customer_care', 'customer_care'), ('intelligence', 'intelligence'), ('product_merchandising', 'product_merchandising'), ('marketing', 'marketing'), ('finance_accounting', 'finance_accounting')], default='sales_overview', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('sales_overview', 'sales_overview'), ('order_attribution', 'order_attribution'), ('performance_analytics', 'performance_analytics'), ('sales_forecasting', 'sales_forecasting'), ('retail_crm_leads', 'retail_crm_leads'), ('quotation_tracker', 'quotation_tracker'), ('cart_recovery', 'cart_recovery'), ('shopify_analytics', 'shopify_analytics'), ('marketplace', 'marketplace'), ('operations', 'operations'), ('logistics', 'logistics'), ('rto_engine', 'rto_engine'), ('customer_care', 'customer_care'), ('intelligence', 'intelligence'), ('product_merchandising', 'product_merchandising'), ('marketing', 'marketing'), ('finance_accounting', 'finance_accounting')], max_length=50),
        ),
    ]
