# Generated by Django 5.1.1 on 2026-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0207_officelocation_idle_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='idle_timeout_enabled',
            field=models.BooleanField(default=True, help_text='Whether the inactivity alarm is enabled'),
        ),
    ]
