# Generated by Django 5.1.1 on 2026-06-18 13:09

from django.db import migrations, models

def backfill_work_mode(apps, schema_editor):
    AttendanceEntry = apps.get_model('core', 'AttendanceEntry')
    AttendanceSession = apps.get_model('core', 'AttendanceSession')
    
    for entry in AttendanceEntry.objects.all():
        if entry.status == 'wfh':
            entry.work_mode = 'wfh'
        elif entry.status == 'present':
            entry.work_mode = 'wfo'
        else:
            # Check sessions
            session = AttendanceSession.objects.filter(
                user=entry.user,
                login_at__date=entry.entry_date
            ).order_by('-login_at').first()
            if session:
                entry.work_mode = session.work_mode
            else:
                # Fallback based on status
                if entry.status == 'half_day':
                    entry.work_mode = 'wfo'
                else:
                    entry.work_mode = 'unknown'
        entry.save(update_fields=['work_mode'])

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_officelocation_idle_timeout_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='work_mode',
            field=models.CharField(choices=[('wfo', 'Work From Office'), ('wfh', 'Work From Home'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.RunPython(backfill_work_mode, reverse_backfill),
    ]
