# Generated by Django 5.2.15 on 2026-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership & Strategy'), ('product', 'Product & Merchandising'), ('branding', 'Branding & Creative'), ('marketing', 'Marketing & Growth'), ('ecommerce', 'E-Commerce & Website'), ('operations', 'Operations & Fulfilment'), ('tracking', 'Logistics'), ('rto_management', 'Reverse Shipment'), ('taskmanager', 'My Desk'), ('customerExperience', 'Customer Experience'), ('intelligence', 'Intelligence'), ('webhooks', 'Webhooks'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('it', 'IT & Data'), ('production', 'Production / Manufacturing'), ('sales', 'Sales & Business Dev')], default='sales_overview', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership & Strategy'), ('product', 'Product & Merchandising'), ('branding', 'Branding & Creative'), ('marketing', 'Marketing & Growth'), ('ecommerce', 'E-Commerce & Website'), ('operations', 'Operations & Fulfilment'), ('tracking', 'Logistics'), ('rto_management', 'Reverse Shipment'), ('taskmanager', 'My Desk'), ('customerExperience', 'Customer Experience'), ('intelligence', 'Intelligence'), ('webhooks', 'Webhooks'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('it', 'IT & Data'), ('production', 'Production / Manufacturing'), ('sales', 'Sales & Business Dev')], max_length=50),
        ),
    ]
