# Generated by Django 5.2.15 on 2026-06-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_order_confirmation_reason_order_hold_reason'),
        ('core', '0209_alter_notification_category_and_more'),
    ]

    operations = [
    ]
