# Generated by Django 5.1.1 on 2026-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_attendanceentry_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeip',
            name='ip_cidr',
            field=models.CharField(blank=True, help_text="Optional CIDR subnet range (e.g. '110.226.173.0/24') for dynamic IP matching", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='require_dual_signal',
            field=models.BooleanField(default=False, help_text='Whether BOTH IP matching and GPS location are required to mark WFO'),
        ),
        migrations.AlterField(
            model_name='officeip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='officeip',
            constraint=models.UniqueConstraint(fields=('office', 'ip_cidr'), name='uniq_office_cidr'),
        ),
    ]
