# Generated by Django 5.1.1 on 2026-06-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_add_cidr_dual_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='logout_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual Logout'), ('midnight_job', 'Midnight Auto-Logout'), ('idle', 'Idle Timeout'), ('page_unload', 'Page Unload'), ('superseded', 'Superseded')], default='', max_length=20),
        ),
    ]
