# Generated by Django 5.1.1 on 2026-06-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_alter_attendancesession_logout_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcemember',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcemember',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSessionExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('exemption_type', models.CharField(choices=[('all', 'Exempt from all anomaly checks'), ('ip_mismatch', 'Exempt from IP mismatch checks'), ('gps_precision', 'Exempt from GPS precision checks'), ('location_jump', 'Exempt from Location jump checks')], default='all', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_exemptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('optional', 'Optional')], default='national', max_length=20)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('org_id', 'date')},
            },
        ),
    ]
