# Generated by Django 5.1.1 on 2026-06-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0212_attendancesession_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcredentials',
            name='global_idle_timeout_enabled',
            field=models.BooleanField(default=True, help_text='Default toggle status for idle timer buzzer across all workspaces/users'),
        ),
        migrations.AddField(
            model_name='shopcredentials',
            name='global_idle_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Default timeout in minutes before triggering inactivity buzzer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idle_timeout_override_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idle_timeout_override_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
