# Generated by Django 5.1.1 on 2026-06-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_alter_notification_category_and_more'),
        ('core', '0213_shopcredentials_global_idle_timeout_enabled_and_more'),
    ]

    operations = [
    ]
