# Generated by Django 5.1.1 on 2026-06-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_merge_20260618_1529'),
        ('core', '0214_merge_20260620_1407'),
    ]

    operations = [
    ]
