# Generated by Django 5.2.14 on 2026-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_incentiverule_salesactivity_salesactivityproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesactivity',
            name='activities_performed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesactivity',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='sales_activities/images/'),
        ),
        migrations.AddField(
            model_name='salesactivity',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='sales_activities/invoices/'),
        ),
    ]
