# Generated by Django 5.1.1 on 2026-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_merge_20260622_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
