# Generated by Django 5.1.1 on 2026-06-22 12:55

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_alter_trackingevent_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCustomApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Custom App',
                'verbose_name_plural': 'Shopify Custom Apps',
            },
        ),
    ]
