# Generated by Django 5.2.14 on 2026-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_salesactivity_activities_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesactivity',
            name='activities_performed',
            field=models.JSONField(blank=True, default=list, help_text='List of activity types performed during the visit'),
        ),
    ]
