# Generated by Django 5.1.1 on 2026-06-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_shopifycustomapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
