# Generated by Django 5.2.14 on 2026-06-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_salesactivity_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('gateway_name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('org_id', 'gateway_name')},
            },
        ),
        migrations.CreateModel(
            name='PrepaidRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('gateway_name', models.CharField(blank=True, max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_settlement_date', models.DateField(blank=True, null=True)),
                ('actual_settlement_date', models.DateField(blank=True, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delay_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Overdue', 'Overdue'), ('Mismatch', 'Mismatch')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_remittances', to='core.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-expected_settlement_date'], name='idx_pp_status_date')],
            },
        ),
    ]
