# Generated by Django 5.2.14 on 2026-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_paymentgatewayfeerule_prepaidremittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayfeerule',
            name='settlement_days',
            field=models.IntegerField(default=2),
        ),
    ]
