# Generated by Django 5.2.14 on 2026-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_alter_order_created_at_and_more'),
        ('core', '0219_paymentgatewayfeerule_settlement_days'),
    ]

    operations = [
    ]
