# Generated by Django 5.1.1 on 2026-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_job_google_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
