# Generated by Django 5.1.1 on 2026-05-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_application_is_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='hiring.job')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('job', 'name')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hiring.jobpipelinestage'),
        ),
    ]
