# Generated by Django 5.1.1 on 2026-06-10 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave')], default='offline', max_length=20)),
                ('leave_active', models.BooleanField(default=False)),
                ('meeting_active', models.BooleanField(default=False)),
                ('manual_status', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave')], max_length=20, null=True)),
                ('activity_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
