# Generated by Django 5.1.1 on 2026-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave'), ('working_remotely', 'Working Remotely')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='activity_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave'), ('working_remotely', 'Working Remotely')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave'), ('working_remotely', 'Working Remotely')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='resolved_status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_meeting', 'In a Meeting'), ('on_leave', 'On Leave'), ('working_remotely', 'Working Remotely')], default='offline', max_length=20),
        ),
    ]
