# Generated by Django 5.1.1 on 2026-05-13 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyCollectionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50)),
                ('shopify_id', models.BigIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'synced_at'], name='inventory_s_organiz_53ae3b_idx')],
                'unique_together': {('organization_id', 'shopify_id')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50)),
                ('shopify_id', models.BigIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'synced_at'], name='inventory_s_organiz_d566e5_idx')],
                'unique_together': {('organization_id', 'shopify_id')},
            },
        ),
    ]
