# Generated by Django 5.2.15 on 2026-06-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_shopify_cache_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('gst_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=50)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('in_process', 'In Process'), ('dispatched', 'Dispatched'), ('received', 'Received')], default='order_placed', max_length=20)),
                ('products', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_qty', models.JSONField(default=dict)),
                ('damaged_qty', models.JSONField(default=dict)),
                ('qc_status', models.CharField(blank=True, default='', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('stock_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
