# Generated by Django 5.1.1 on 2026-05-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='actlog_ts_idx',
        ),
    ]
