# Generated by Django 5.1.1 on 2026-06-13 04:44

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('compliance', 'Compliance'), ('skills', 'Skills'), ('sops', 'SOPs')], default='onboarding', max_length=50)),
                ('file', models.FileField(storage=core.storage.AutoResourceCloudinaryStorage(), upload_to='hr/training/')),
                ('department_target', models.CharField(blank=True, default='', max_length=100)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='training.trainingfile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_training_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('target_departments', models.JSONField(blank=True, default=list)),
                ('pushed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_pushes', to=settings.AUTH_USER_MODEL)),
                ('training_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to='training.trainingfile')),
            ],
            options={
                'ordering': ['-pushed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPushRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='training.trainingpush')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_recipient_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('push', 'user')},
            },
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='target_members',
            field=models.ManyToManyField(related_name='assigned_training_pushes', through='training.TrainingPushRecipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=64)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('training_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='training.trainingfile')),
                ('push_recipient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='training.trainingpushrecipient')),
            ],
            options={
                'unique_together': {('training_file', 'user')},
            },
        ),
    ]
