# Generated by Django 5.1.1 on 2026-06-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingacknowledgement',
            options={'ordering': ['-acknowledged_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingpushrecipient',
            options={'ordering': ['user__first_name']},
        ),
        migrations.RemoveField(
            model_name='trainingpush',
            name='target_members',
        ),
        migrations.AddField(
            model_name='trainingacknowledgement',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingacknowledgement',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='file_size_kb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='training.trainingfile'),
        ),
        migrations.AddField(
            model_name='trainingfile',
            name='target_dept',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='create_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='notify_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='vault_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingpush',
            name='vault_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='trainingacknowledgement',
            name='org_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='trainingfile',
            name='category',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('compliance', 'Compliance'), ('skills', 'Skills'), ('sops', 'SOPs')], default='onboarding', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingfile',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
