# Generated by Django 5.1.1 on 2026-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_add_vault_and_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingfile',
            name='category',
            field=models.CharField(default='onboarding', max_length=50),
        ),
    ]
