# Generated by Django 5.1.1 on 2026-06-13 08:27

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_trainingfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfile',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.AutoResourceCloudinaryStorage(), upload_to='hr/training/'),
        ),
    ]
